
const creatorMode = true;

const ItemCards = [ 
/***** 
D E B U G
*****/
{   layout: ItemCard , type:Asset.card.item.beispiel , qty: 0 ,
    name:{ de:"AllInExample", en:"" }, weight: 2 ,
    flavor:{ de:"", en:"" },
    keyword : {
        clothing : { _isFragile : true ,
            coldProt : 1 , wetProt : 1 , windProt : 1 , storage : 1 , dmgProt : 1 ,
            custom : `` },

        tool : {  _isFragile : true ,
            crafting   : 1 , chopping    : 1 , kindle : 1 , light : 1 ,
            lookout    : 1 , navigation  : 1 , 
            meleeLight : 1 , meleeHeavy  : 1 , ranged : 1 , magic : 1 ,
            custom : `` },

        material : { _isFragile : true ,
            structural : 1 , metallic : 1 , sharp     : 1 , shaft : 1 ,
            cordage    : 1 , cover : 1 , adhesive : 1 , flammable : 1 ,
            custom : `` },

        supply : { _isPerishable : true ,
            exhaustion : 1 , hunger : 1 , hypothermia : 1 , wound    : 1 , 
            herb       : 1 , nut    : 1 , root        : 1 , mushroom : 1 , berry : 1 ,
            custom : `` },
    },
},
{   layout: ItemCard , type:Asset.card.item.beispiel , qty: 0 ,
    name:{ de:"AllOutExample", en:"" }, weight: 0 ,
    flavor:{ de:"", en:"" },
    keyword : {
        clothing : { _isFragile : false ,
            coldProt : 0 , wetProt : 0 , windProt : 0 , storage : 0 , dmgProt : 0 ,
            custom : `` },

        tool : {  _isFragile : false ,
            crafting   : 0 , chopping    : 0 , kindle : 0 , light : 0 ,
            lookout    : 0 , navigation  : 0 ,
            meleeLight : 0 , meleeHeavy  : 0 , ranged : 0 , magic : 0 ,
            custom : `` },

        material : { _isFragile : true ,
            structural : 0 , metallic : 0 , sharp     : 0 , shaft : 0 ,
            cordage    : 0 , cover : 0 , adhesive : 0 , flammable : 0 ,
            custom : `` },

        supply : { _isPerishable : false ,
            exhaustion : 0 , hunger : 0 , hypothermia : 0 , wound    : 0 , 
            herb       : 0 , nut    : 0 , root        : 0 , mushroom : 0 , berry : 0 ,
            custom : `` },
    },
},
/***** 
S H I P 
*****/
// ---------------------
// CLOTHING & WEARABLES
// ---------------------
{   layout: ItemCard , type:Asset.card.item.ship , qty: 3 ,
    name:{ de:"Leinenhemd", en:"Linen clothing" }, weight: 0 ,
    flavor:{ de:"Grobes, graues Leinenhemd", en:"" },
    keyword : {
        clothing : { _isFragile : false ,
            coldProt : 1 , wetProt : 0 , windProt : 0 , storage : 0 , dmgProt : 0 ,
            custom : `` },

        tool : {  _isFragile : false ,
            crafting   : 0 , chopping    : 0 , kindle : 0 , light : 0 ,
            lookout    : 0 , navigation  : 0 ,
            meleeLight : 0 , meleeHeavy  : 0 , ranged : 0 , magic : 0 ,
            custom : `` },

        material : { _isFragile : false ,
            structural : 0 , metallic : 0 , sharp     : 0 , shaft : 0 ,
            cordage    : 1 , cover : 0 , adhesive : 0 , flammable : 1 ,
            custom : `` },

        supply : { _isPerishable : false ,
            exhaustion : 0 , hunger : 0 , hypothermia : 0 , wound    : 0 , 
            herb       : 0 , nut    : 0 , root        : 0 , mushroom : 0 , berry : 0 ,
            custom : `` },
    },
},
{   layout: ItemCard , type:Asset.card.item.ship , qty: 3 ,
    name:{ de:"Wollhemd", en:"" }, weight: 0 ,
    flavor:{ de:"Warmer, robuster Kälteschutz", en:"" },
    keyword : {
        clothing : { _isFragile : false ,
            coldProt : 1 , wetProt : 1 , windProt : 0 , storage : 0 , dmgProt : 0 ,
            custom : `` },

        tool : {  _isFragile : false ,
            crafting   : 0 , chopping    : 0 , kindle : 0 , light : 0 ,
            lookout    : 0 , navigation  : 0 ,
            meleeLight : 0 , meleeHeavy  : 0 , ranged : 0 , magic : 0 ,
            custom : `` },

        material : { _isFragile : false ,
            structural : 0 , metallic : 0 , sharp     : 0 , shaft : 0 ,
            cordage    : 1 , cover : 1 , adhesive : 0 , flammable : 0 ,
            custom : `` },

        supply : { _isPerishable : false ,
            exhaustion : 0 , hunger : 0 , hypothermia : 0 , wound    : 0 , 
            herb       : 0 , nut    : 0 , root        : 0 , mushroom : 0 , berry : 0 ,
            custom : `` },
    },
},
{   layout: ItemCard , type:Asset.card.item.ship , qty: 2 ,
    name:{ de:"Canvasjacke", en:"" }, weight: 0 ,
    flavor:{ de:"Diente Seeleuten, Fischern und Arbeitern als extrem reißfester, wind- und wetterfester Schutz", en:"" },
    keyword : {
        clothing : { _isFragile : false ,
            coldProt : 1 , wetProt : 2 , windProt : 1 , storage : 0 , dmgProt : 0 ,
            custom : `` },

        tool : {  _isFragile : false ,
            crafting   : 0 , chopping    : 0 , kindle : 0 , light : 0 ,
            lookout    : 0 , navigation  : 0 ,
            meleeLight : 0 , meleeHeavy  : 0 , ranged : 0 , magic : 0 ,
            custom : `` },

        material : { _isFragile : false ,
            structural : 0 , metallic : 0 , sharp     : 0 , shaft : 0 ,
            cordage    : 1 , cover : 1 , adhesive : 0 , flammable : 1 ,
            custom : `` },

        supply : { _isPerishable : false ,
            exhaustion : 0 , hunger : 0 , hypothermia : 0 , wound    : 0 , 
            herb       : 0 , nut    : 0 , root        : 0 , mushroom : 0 , berry : 0 ,
            custom : `` },
    },
},
{   layout: ItemCard , type:Asset.card.item.ship , qty: 2 ,
    name:{ de:"Lederweste", en:"" }, weight: 0 ,
    flavor:{ de:"robuste, schützende Arbeitskleidung", en:"" },
    keyword : {
        clothing : { _isFragile : false ,
            coldProt : 1 , wetProt : 1 , windProt : 0 , storage : 0 , dmgProt : 1 ,
            custom : `` },

        tool : {  _isFragile : false ,
            crafting   : 0 , chopping    : 0 , kindle : 0 , light : 0 ,
            lookout    : 0 , navigation  : 0 ,
            meleeLight : 0 , meleeHeavy  : 0 , ranged : 0 , magic : 0 ,
            custom : `` },

        material : { _isFragile : false ,
            structural : 0 , metallic : 0 , sharp     : 0 , shaft : 0 ,
            cordage    : 1 , cover : 1 , adhesive : 0 , flammable : 0 ,
            custom : `` },

        supply : { _isPerishable : false ,
            exhaustion : 0 , hunger : 0 , hypothermia : 0 , wound    : 0 , 
            herb       : 0 , nut    : 0 , root        : 0 , mushroom : 0 , berry : 0 ,
            custom : `` },
    },
},
{   layout: ItemCard , type:Asset.card.item.ship , qty: 1 ,
    name:{ de:"Ledermantel", en:"" }, weight: 0 ,
    flavor:{ de:"extreme Haltbarkeit bei harter körperlicher Arbei", en:"" },
    keyword : {
        clothing : { _isFragile : false ,
            coldProt : 1 , wetProt : 2 , windProt : 1 , storage : 0 , dmgProt : 1 ,
            custom : `` },

        tool : {  _isFragile : false ,
            crafting   : 0 , chopping    : 0 , kindle : 0 , light : 0 ,
            lookout    : 0 , navigation  : 0 ,
            meleeLight : 0 , meleeHeavy  : 0 , ranged : 0 , magic : 0 ,
            custom : `` },

        material : { _isFragile : false ,
            structural : 0 , metallic : 0 , sharp     : 0 , shaft : 0 ,
            cordage    : 1 , cover : 1 , adhesive : 0 , flammable : 0 ,
            custom : `` },

        supply : { _isPerishable : false ,
            exhaustion : 0 , hunger : 0 , hypothermia : 0 , wound    : 0 , 
            herb       : 0 , nut    : 0 , root        : 0 , mushroom : 0 , berry : 0 ,
            custom : `` },
    },
},
// ---------------------
// TOOLS
// ---------------------
{   layout: ItemCard , type:Asset.card.item.ship , qty: 1 ,
    name:{ de:"Handbeil", en:"" }, weight: 0 ,
    flavor:{ de:"Klein, leicht und einhändig geführt, diente es zum Anspitzen von Pflöcken, Entasten und für feine Holzarbeiten", en:"" },
    keyword : {
        clothing : { _isFragile : false ,
            coldProt : 0 , wetProt : 0 , windProt : 0 , storage : 0 , dmgProt : 0 ,
            custom : `` },

        tool : {  _isFragile : false ,
            crafting   : 1 , chopping    : 1 , kindle : 0 , light : 0 ,
            lookout    : 0 , navigation  : 0 ,
            meleeLight : 1 , meleeHeavy  : 0 , ranged : 0 , magic : 0 ,
            custom : `` },

        material : { _isFragile : false ,
            structural : 0 , metallic : 1 , sharp     : 1 , shaft : 1 ,
            cordage    : 0 , cover : 0 , adhesive : 0 , flammable : 1 ,
            custom : `` },

        supply : { _isPerishable : false ,
            exhaustion : 0 , hunger : 0 , hypothermia : 0 , wound    : 0 , 
            herb       : 0 , nut    : 0 , root        : 0 , mushroom : 0 , berry : 0 ,
            custom : `` },
    },
},
{   layout: ItemCard , type:Asset.card.item.ship , qty: 1 ,
    name:{ de:"Breitaxt", en:"" }, weight: 1 ,
    flavor:{ de:"Ein unverzichtbares Werkzeug des traditionellen Zimmerhandwerks", en:"" },
    keyword : {
        clothing : { _isFragile : false ,
            coldProt : 0 , wetProt : 0 , windProt : 0 , storage : 0 , dmgProt : 0 ,
            custom : `` },

        tool : {  _isFragile : false ,
            crafting   : 0 , chopping    : 1 , kindle : 0 , light : 0 ,
            lookout    : 0 , navigation  : 0 ,
            meleeLight : 1 , meleeHeavy  : 0 , ranged : 0 , magic : 0 ,
            custom : `` },

        material : { _isFragile : false ,
            structural : 0 , metallic : 1 , sharp     : 1 , shaft : 1 ,
            cordage    : 0 , cover : 0 , adhesive : 0 , flammable : 1 ,
            custom : `` },

        supply : { _isPerishable : false ,
            exhaustion : 0 , hunger : 0 , hypothermia : 0 , wound    : 0 , 
            herb       : 0 , nut    : 0 , root        : 0 , mushroom : 0 , berry : 0 ,
            custom : `` },
    },
},
{   layout: ItemCard , type:Asset.card.item.ship , qty: 1 ,
    name:{ de:"Fällaxt", en:"" }, weight: 1 ,
    flavor:{ de:"Zum Fällen von ganzen Bäumen und Trennen des Stammes", en:"" },
    keyword : {
        clothing : { _isFragile : false ,
            coldProt : 0 , wetProt : 0 , windProt : 0 , storage : 0 , dmgProt : 0 ,
            custom : `` },

        tool : {  _isFragile : false ,
            crafting   : 0 , chopping    : 1 , kindle : 0 , light : 0 ,
            lookout    : 0 , navigation  : 0 ,
            meleeLight : 0 , meleeHeavy  : 1 , ranged : 0 , magic : 0 ,
            custom : `+1 ${Asset.tile.action.chopping.icon}` },

        material : { _isFragile : false ,
            structural : 0 , metallic : 1 , sharp     : 1 , shaft : 1 ,
            cordage    : 0 , cover : 0 , adhesive : 0 , flammable : 1 ,
            custom : `` },

        supply : { _isPerishable : false ,
            exhaustion : 0 , hunger : 0 , hypothermia : 0 , wound    : 0 , 
            herb       : 0 , nut    : 0 , root        : 0 , mushroom : 0 , berry : 0 ,
            custom : `` },
    },
},
{   layout: ItemCard , type:Asset.card.item.ship , qty: 1 ,
    name:{ de:"Spaltaxt", en:"" }, weight: 1 ,
    flavor:{ de:"Zum Spalten von bereits abgelängten Baumscheiten", en:"" },
    keyword : {
        clothing : { _isFragile : false ,
            coldProt : 0 , wetProt : 0 , windProt : 0 , storage : 0 , dmgProt : 0 ,
            custom : `` },

        tool : {  _isFragile : false ,
            crafting   : 0 , chopping    : 1 , kindle : 0 , light : 0 ,
            lookout    : 0 , navigation  : 0 ,
            meleeLight : 0 , meleeHeavy  : 1 , ranged : 0 , magic : 0 ,
            custom : `` },

        material : { _isFragile : false ,
            structural : 0 , metallic : 1 , sharp     : 1 , shaft : 1 ,
            cordage    : 0 , cover : 0 , adhesive : 0 , flammable : 1 ,
            custom : `` },

        supply : { _isPerishable : false ,
            exhaustion : 0 , hunger : 0 , hypothermia : 0 , wound    : 0 , 
            herb       : 0 , nut    : 0 , root        : 0 , mushroom : 0 , berry : 0 ,
            custom : `` },
    },
},
{   layout: ItemCard , type:Asset.card.item.ship , qty: 3 ,
    name:{ de:"Schlagfeuerzeug", en:"" }, weight: 0 ,
    flavor:{ de:"Durch das Schlagen des Stahls gegen den Stein werden heiße Funken erzeugt", en:"" },
    keyword : {
        custom   : [  ],
        
        clothing : { _isFragile : false ,
            coldProt : 0 , wetProt : 0 , windProt : 0 , storage : 0 , dmgProt : 0 ,
            custom : `` },

        tool : {  _isFragile : false ,
            crafting   : 0 , chopping    : 0 , kindle : 1 , light : 0 ,
            lookout    : 0 , navigation  : 0 ,
            meleeLight : 0 , meleeHeavy  : 0 , ranged : 0 , magic : 0 ,
            custom : `` },

        material : { _isFragile : false ,
            structural : 0 , metallic : 1 , sharp     : 0 , shaft : 0 ,
            cordage    : 0 , cover : 0 , adhesive : 0 , flammable : 0 ,
            custom : `` },

        supply : { _isPerishable : false ,
            exhaustion : 0 , hunger : 0 , hypothermia : 0 , wound    : 0 , 
            herb       : 0 , nut    : 0 , root        : 0 , mushroom : 0 , berry : 0 ,
            custom : `` },
    },
},
{   layout: ItemCard , type:Asset.card.item.ship , qty: 3 ,
    name:{ de:"Nähzeug", en:"" }, weight: 0 ,
    flavor:{ de:"Nadel und Faden", en:"" },
    keyword : {
        clothing : { _isFragile : false ,
            coldProt : 0 , wetProt : 0 , windProt : 0 , storage : 0 , dmgProt : 0 ,
            custom : `` },

        tool : {  _isFragile : false ,
            crafting   : 0 , chopping    : 0 , kindle : 0 , light : 0 ,
            lookout    : 0 , navigation  : 0 ,
            meleeLight : 0 , meleeHeavy  : 0 , ranged : 0 , magic : 0 ,
            custom : `` },

        material : { _isFragile : false ,
            structural : 0 , metallic : 0 , sharp     : 0 , shaft : 0 ,
            cordage    : 1 , cover : 0 , adhesive : 0 , flammable : 1 ,
            custom : `` },

        supply : { _isPerishable : false ,
            exhaustion : 0 , hunger : 0 , hypothermia : 0 , wound    : 0 , 
            herb       : 0 , nut    : 0 , root        : 0 , mushroom : 0 , berry : 0 ,
            custom : `` },
    },
},
// ---------------------
// SHIP
// ---------------------
{   layout: ItemCard , type:Asset.card.item.ship , qty: 1 ,
    name:{ de:"Kompass", en:"" }, weight: 0 ,
    flavor:{ de:"Neben der Seefahrt diente er Landvermessern, Militärs und wohlhabenden Reisenden", en:"" },
    keyword : {
        clothing : { _isFragile : false ,
            coldProt : 0 , wetProt : 0 , windProt : 0 , storage : 0 , dmgProt : 0 ,
            custom : `` },

        tool : {  _isFragile : false ,
            crafting   : 0 , chopping    : 0 , kindle : 0 , light : 0 ,
            lookout    : 0 , navigation  : 1 ,
            meleeLight : 0 , meleeHeavy  : 0 , ranged : 0 , magic : 0 ,
            custom : `` },

        material : { _isFragile : false ,
            structural : 0 , metallic : 1 , sharp     : 0 , shaft : 0 ,
            cordage    : 0 , cover : 0 , adhesive : 0 , flammable : 0 ,
            custom : `` },

        supply : { _isPerishable : false ,
            exhaustion : 0 , hunger : 0 , hypothermia : 0 , wound    : 0 , 
            herb       : 0 , nut    : 0 , root        : 0 , mushroom : 0 , berry : 0 ,
            custom : `` },
    },
},
{   layout: ItemCard , type:Asset.card.item.ship , qty: 1 ,
    name:{ de:"Fernrohr", en:"" }, weight: 0 ,
    flavor:{ de:"Hilft bei der Navigation", en:"" },
    keyword : {
        clothing : { _isFragile : false ,
            coldProt : 0 , wetProt : 0 , windProt : 0 , storage : 0 , dmgProt : 0 ,
            custom : `` },

        tool : {  _isFragile : false ,
            crafting   : 0 , chopping    : 0 , kindle : 0 , light : 0 ,
            lookout    : 1 , navigation  : 1 ,
            meleeLight : 0 , meleeHeavy  : 0 , ranged : 0 , magic : 0 ,
            custom : `` },

        material : { _isFragile : false ,
            structural : 0 , metallic : 1 , sharp     : 0 , shaft : 0 ,
            cordage    : 0 , cover : 0 , adhesive : 0 , flammable : 0 ,
            custom : `` },

        supply : { _isPerishable : false ,
            exhaustion : 0 , hunger : 0 , hypothermia : 0 , wound    : 0 , 
            herb       : 0 , nut    : 0 , root        : 0 , mushroom : 0 , berry : 0 ,
            custom : `` },
    },
},
{   layout: ItemCard , type:Asset.card.item.ship , qty: 1 ,
    name:{ de:"Karte", en:"" }, weight: 0 ,
    flavor:{ de:"Zum Ablesen und Halten von Kursen", en:"" },
    keyword : {
        clothing : { _isFragile : false ,
            coldProt : 0 , wetProt : 0 , windProt : 0 , storage : 0 , dmgProt : 0 ,
            custom : `` },

        tool : {  _isFragile : false ,
            crafting   : 0 , chopping    : 0 , kindle : 0 , light : 0 ,
            lookout    : 0 , navigation  : 1 ,
            meleeLight : 0 , meleeHeavy  : 0 , ranged : 0 , magic : 0 ,
            custom : `` },

        material : { _isFragile : false ,
            structural : 0 , metallic : 0 , sharp     : 0 , shaft : 0 ,
            cordage    : 0 , cover : 0 , adhesive : 0 , flammable : 1 ,
            custom : `` },

        supply : { _isPerishable : false ,
            exhaustion : 0 , hunger : 0 , hypothermia : 0 , wound    : 0 , 
            herb       : 0 , nut    : 0 , root        : 0 , mushroom : 0 , berry : 0 ,
            custom : `` },
    },
},
{   layout: ItemCard , type:Asset.card.item.ship , qty: 2 ,
    name:{ de:"Segel", en:"" }, weight: 0 ,
    flavor:{ de:"Besteht aus robusten Leinen", en:"" },
    keyword : {
        clothing : { _isFragile : false ,
            coldProt : 0 , wetProt : 0 , windProt : 0 , storage : 0 , dmgProt : 0 ,
            custom : `` },

        tool : {  _isFragile : false ,
            crafting   : 0 , chopping    : 0 , kindle : 0 , light : 0 ,
            lookout    : 0 , navigation  : 0 ,
            meleeLight : 0 , meleeHeavy  : 0 , ranged : 0 , magic : 0 ,
            custom : `` },

        material : { _isFragile : false ,
            structural : 0 , metallic : 0 , sharp     : 0 , shaft : 0 ,
            cordage    : 1 , cover : 1 , adhesive : 0 , flammable : 1 ,
            custom : `` },

        supply : { _isPerishable : false ,
            exhaustion : 0 , hunger : 0 , hypothermia : 0 , wound    : 0 , 
            herb       : 0 , nut    : 0 , root        : 0 , mushroom : 0 , berry : 0 ,
            custom : `` },
    },
},
{   layout: ItemCard , type:Asset.card.item.ship , qty: 3 ,
    name:{ de:"Seil", en:"" }, weight: 0 ,
    flavor:{ de:"Ein langer, reißfester Strang aus verdrillten und geflochtenen Fasern", en:"" },
    keyword : {
        clothing : { _isFragile : false ,
            coldProt : 0 , wetProt : 0 , windProt : 0 , storage : 0 , dmgProt : 0 ,
            custom : `` },

        tool : {  _isFragile : false ,
            crafting   : 0 , chopping    : 0 , kindle : 0 , light : 0 ,
            lookout    : 0 , navigation  : 0 ,
            meleeLight : 0 , meleeHeavy  : 0 , ranged : 0 , magic : 0 ,
            custom : `` },

        material : { _isFragile : false ,
            structural : 0 , metallic : 0 , sharp     : 0 , shaft : 0 ,
            cordage    : 1 , cover : 0 , adhesive : 0 , flammable : 1 ,
            custom : `` },

        supply : { _isPerishable : false ,
            exhaustion : 0 , hunger : 0 , hypothermia : 0 , wound    : 0 , 
            herb       : 0 , nut    : 0 , root        : 0 , mushroom : 0 , berry : 0 ,
            custom : `` },
    },
},
{   layout: ItemCard , type:Asset.card.item.ship , qty: 2 ,
    name:{ de:"Maststück", en:"" }, weight: 1 ,
    flavor:{ de:"Ein Stück der mächtigen Masten", en:"" },
    keyword : {
        clothing : { _isFragile : false ,
            coldProt : 0 , wetProt : 0 , windProt : 0 , storage : 0 , dmgProt : 0 ,
            custom : `` },

        tool : {  _isFragile : false ,
            crafting   : 0 , chopping    : 0 , kindle : 0 , light : 0 ,
            lookout    : 0 , navigation  : 0 ,
            meleeLight : 0 , meleeHeavy  : 0 , ranged : 0 , magic : 0 ,
            custom : `` },

        material : { _isFragile : false ,
            structural : 1 , metallic : 0 , sharp     : 0 , shaft : 1 ,
            cordage    : 0 , cover : 0 , adhesive : 0 , flammable : 1 ,
            custom : `` },

        supply : { _isPerishable : false ,
            exhaustion : 0 , hunger : 0 , hypothermia : 0 , wound    : 0 , 
            herb       : 0 , nut    : 0 , root        : 0 , mushroom : 0 , berry : 0 ,
            custom : `` },
    },
},
{   layout: ItemCard , type:Asset.card.item.ship , qty: 3 ,
    name:{ de:"Schiffshülle", en:"" }, weight: 1 ,
    flavor:{ de:"Ein Stück der Schiffshülle", en:"" },
    keyword : {
        clothing : { _isFragile : false ,
            coldProt : 0 , wetProt : 0 , windProt : 0 , storage : 0 , dmgProt : 0 ,
            custom : `` },

        tool : {  _isFragile : false ,
            crafting   : 0 , chopping    : 0 , kindle : 0 , light : 0 ,
            lookout    : 0 , navigation  : 0 ,
            meleeLight : 0 , meleeHeavy  : 0 , ranged : 0 , magic : 0 ,
            custom : `` },

        material : { _isFragile : false ,
            structural : 1 , metallic : 0 , sharp     : 0 , shaft : 0 ,
            cordage    : 0 , cover : 1 , adhesive : 0 , flammable : 1 ,
            custom : `` },

        supply : { _isPerishable : false ,
            exhaustion : 0 , hunger : 0 , hypothermia : 0 , wound    : 0 , 
            herb       : 0 , nut    : 0 , root        : 0 , mushroom : 0 , berry : 0 ,
            custom : `` },
    },
},
// ---------------------
// WEAPONS
// ---------------------
{   layout: ItemCard , type:Asset.card.item.ship , qty: 2 ,
    name:{ de:"Hirschfänger", en:"" }, weight: 0 ,
    flavor:{ de:"Ein kurzes, schweres Messer zum Abfangen von Wild", en:"" },
    keyword : {
        clothing : { _isFragile : false ,
            coldProt : 0 , wetProt : 0 , windProt : 0 , storage : 0 , dmgProt : 0 ,
            custom : `` },

        tool : {  _isFragile : false ,
            crafting   : 1 , chopping    : 0 , kindle : 0 , light : 0 ,
            lookout    : 0 , navigation  : 0 ,
            meleeLight : 1 , meleeHeavy  : 0 , ranged : 0 , magic : 0 ,
            custom : `` },

        material : { _isFragile : false ,
            structural : 0 , metallic : 1 , sharp     : 1 , shaft : 0 ,
            cordage    : 0 , cover : 0 , adhesive : 0 , flammable : 0 ,
            custom : `` },

        supply : { _isPerishable : false ,
            exhaustion : 0 , hunger : 0 , hypothermia : 0 , wound    : 0 , 
            herb       : 0 , nut    : 0 , root        : 0 , mushroom : 0 , berry : 0 ,
            custom : `` },
    },
},
{   layout: ItemCard , type:Asset.card.item.ship , qty: 1 ,
    name:{ de:"Metzgermesser", en:"" }, weight: 0 ,
    flavor:{ de:"Genau auf das Zerlegen von Fleisch und das Parieren von Sehnen ausgelegt", en:"" },
    keyword : {
        clothing : { _isFragile : false ,
            coldProt : 0 , wetProt : 0 , windProt : 0 , storage : 0 , dmgProt : 0 ,
            custom : `` },

        tool : {  _isFragile : false ,
            crafting   : 1 , chopping    : 0 , kindle : 0 , light : 0 ,
            lookout    : 0 , navigation  : 0 ,
            meleeLight : 1 , meleeHeavy  : 0 , ranged : 0 , magic : 0 ,
            custom : `+1 ${Asset.tile.action.hunting.icon}` },

        material : { _isFragile : false ,
            structural : 0 , metallic : 1 , sharp     : 1 , shaft : 0 ,
            cordage    : 0 , cover : 0 , adhesive : 0 , flammable : 0 ,
            custom : `` },

        supply : { _isPerishable : false ,
            exhaustion : 0 , hunger : 0 , hypothermia : 0 , wound    : 0 , 
            herb       : 0 , nut    : 0 , root        : 0 , mushroom : 0 , berry : 0 ,
            custom : `` },
    },
},
{   layout: ItemCard , type:Asset.card.item.ship , qty: 1 ,
    name:{ de:"Entersäbel", en:"" }, weight: 0 ,
    flavor:{ de:"Im Gegensatz zu feinen Degen erforderte der Entersäbel kaum komplexe Fechtkunst", en:"" },
    keyword : {
        clothing : { _isFragile : false ,
            coldProt : 0 , wetProt : 0 , windProt : 0 , storage : 0 , dmgProt : 0 ,
            custom : `` },

        tool : {  _isFragile : false ,
            crafting   : 0 , chopping    : 0 , kindle : 0 , light : 0 ,
            lookout    : 0 , navigation  : 0 ,
            meleeLight : 0 , meleeHeavy  : 1 , ranged : 0 , magic : 0 ,
            custom : `` },

        material : { _isFragile : false ,
            structural : 0 , metallic : 1 , sharp     : 1 , shaft : 0 ,
            cordage    : 0 , cover : 0 , adhesive : 0 , flammable : 0 ,
            custom : `` },

        supply : { _isPerishable : false ,
            exhaustion : 0 , hunger : 0 , hypothermia : 0 , wound    : 0 , 
            herb       : 0 , nut    : 0 , root        : 0 , mushroom : 0 , berry : 0 ,
            custom : `` },
    },
},
// ---------------------
// MEDICAL
// ---------------------
{   layout: ItemCard , type:Asset.card.item.ship , qty: 4 ,
    name:{ de:"Bandage", en:"" }, weight: 0 ,
    flavor:{ de:"Deckt offene Wunden ab und schützt vor Schmutz", en:"" },
    keyword : {
        clothing : { _isFragile : false ,
            coldProt : 0 , wetProt : 0 , windProt : 0 , storage : 0 , dmgProt : 0 ,
            custom : `` },

        tool : {  _isFragile : false ,
            crafting   : 0 , chopping    : 0 , kindle : 0 , light : 0 ,
            lookout    : 0 , navigation  : 0 ,
            meleeLight : 0 , meleeHeavy  : 0 , ranged : 0 , magic : 0 ,
            custom : `` },

        material : { _isFragile : false ,
            structural : 0 , metallic : 0 , sharp     : 0 , shaft : 0 ,
            cordage    : 1 , cover : 0 , adhesive : 0 , flammable : 1 ,
            custom : `` },

        supply : { _isPerishable : false ,
            exhaustion : 0 , hunger : 0 , hypothermia : 0 , wound    : 1 , 
            herb       : 0 , nut    : 0 , root        : 0 , mushroom : 0 , berry : 0 ,
            custom : `` },
    },
},
{   layout: ItemCard , type:Asset.card.item.ship , qty: 1 ,
    name:{ de:"Operationsbesteck", en:"" }, weight: 0 ,
    flavor:{ de:"Kleine Sägen und Zangen für einen Arzt", en:"" },
    keyword : {
        clothing : { _isFragile : false ,
            coldProt : 0 , wetProt : 0 , windProt : 0 , storage : 0 , dmgProt : 0 ,
            custom : `` },

        tool : {  _isFragile : false ,
            crafting   : 1 , chopping    : 0 , kindle : 0 , light : 0 ,
            lookout    : 0 , navigation  : 0 ,
            meleeLight : 1 , meleeHeavy  : 0 , ranged : 0 , magic : 0 ,
            custom : `` },

        material : { _isFragile : false ,
            structural : 0 , metallic : 1 , sharp     : 1 , shaft : 0 ,
            cordage    : 0 , cover : 0 , adhesive : 0 , flammable : 0 ,
            custom : `` },

        supply : { _isPerishable : false ,
            exhaustion : 0 , hunger : 0 , hypothermia : 0 , wound    : 0 , 
            herb       : 0 , nut    : 0 , root        : 0 , mushroom : 0 , berry : 0 ,
            custom : `` },
    },
},
{   layout: ItemCard , type:Asset.card.item.ship , qty: 2 ,
    name:{ de:"Essig", en:"" }, weight: 0 ,
    flavor:{ de:"Gut zur Desinfektion oder Konservierung", en:"" },
    keyword : {
        clothing : { _isFragile : false ,
            coldProt : 0 , wetProt : 0 , windProt : 0 , storage : 0 , dmgProt : 0 ,
            custom : `` },

        tool : {  _isFragile : false ,
            crafting   : 0 , chopping    : 0 , kindle : 0 , light : 0 ,
            lookout    : 0 , navigation  : 0 ,
            meleeLight : 0 , meleeHeavy  : 0 , ranged : 0 , magic : 0 ,
            custom : `` },

        material : { _isFragile : false ,
            structural : 0 , metallic : 0 , sharp     : 0 , shaft : 0 ,
            cordage    : 0 , cover : 0 , adhesive : 0 , flammable : 1 ,
            custom : `` },

        supply : { _isPerishable : false ,
            exhaustion : 0 , hunger : 0 , hypothermia : 0 , wound    : 1 , 
            herb       : 0 , nut    : 0 , root        : 0 , mushroom : 0 , berry : 0 ,
            custom : `Ignoriere ${Asset.keyword.supply._isPerishable.icon}` },
    },
},
{   layout: ItemCard , type:Asset.card.item.ship , qty: 1 ,
    name:{ de:"Bibel", en:"" }, weight: 0 ,
    flavor:{ de:"Ein unverzichtbarer Begleiter in der Seefahrt", en:"" },
    keyword : {
        clothing : { _isFragile : false ,
            coldProt : 0 , wetProt : 0 , windProt : 0 , storage : 0 , dmgProt : 0 ,
            custom : `` },

        tool : {  _isFragile : false ,
            crafting   : 0 , chopping    : 0 , kindle : 0 , light : 0 ,
            lookout    : 0 , navigation  : 0 ,
            meleeLight : 0 , meleeHeavy  : 0 , ranged : 0 , magic : 0 ,
            custom : `${Asset.keyword.supply.exhaustion.icon} pro Tag` },

        material : { _isFragile : false ,
            structural : 0 , metallic : 0 , sharp     : 0 , shaft : 0 ,
            cordage    : 0 , cover : 0 , adhesive : 0 , flammable : 1 ,
            custom : `${Asset.condition.exhaustion.icon} (alle) wenn verbrannt` },

        supply : { _isPerishable : false ,
            exhaustion : 0 , hunger : 0 , hypothermia : 0 , wound    : 0 , 
            herb       : 0 , nut    : 0 , root        : 0 , mushroom : 0 , berry : 0 ,
            custom : `` },
    },
},
// ---------------------
// FOOD
// ---------------------
{   layout: ItemCard , type:Asset.card.item.ship , qty: 3 ,
    name:{ de:"Pöckelfleisch", en:"" }, weight: 0 ,
    flavor:{ de:"Eine überlebenswichtige Methode, um Fleisch ohne Kühlschränke monatelang haltbar zu machen", en:"" },
    keyword : {
        clothing : { _isFragile : false ,
            coldProt : 0 , wetProt : 0 , windProt : 0 , storage : 0 , dmgProt : 0 ,
            custom : `` },

        tool : {  _isFragile : false ,
            crafting   : 0 , chopping    : 0 , kindle : 0 , light : 0 ,
            lookout    : 0 , navigation  : 0 ,
            meleeLight : 0 , meleeHeavy  : 0 , ranged : 0 , magic : 0 ,
            custom : `` },

        material : { _isFragile : false ,
            structural : 0 , metallic : 0 , sharp     : 0 , shaft : 0 ,
            cordage    : 0 , cover : 0 , adhesive : 0 , flammable : 0 ,
            custom : `` },

        supply : { _isPerishable : false ,
            exhaustion : 0 , hunger : 1 , hypothermia : 0 , wound    : 0 , 
            herb       : 0 , nut    : 0 , root        : 0 , mushroom : 0 , berry : 0 ,
            custom : `` },
    },
},
{   layout: ItemCard , type:Asset.card.item.ship , qty: 3 ,
    name:{ de:"Bohnen", en:"" }, weight: 0 ,
    flavor:{ de:"Eignet sich auch gut als Viehfutter", en:"" },
    keyword : {
        clothing : { _isFragile : false ,
            coldProt : 0 , wetProt : 0 , windProt : 0 , storage : 0 , dmgProt : 0 ,
            custom : `` },

        tool : {  _isFragile : false ,
            crafting   : 0 , chopping    : 0 , kindle : 0 , light : 0 ,
            lookout    : 0 , navigation  : 0 ,
            meleeLight : 0 , meleeHeavy  : 0 , ranged : 0 , magic : 0 ,
            custom : `` },

        material : { _isFragile : false ,
            structural : 0 , metallic : 0 , sharp     : 0 , shaft : 0 ,
            cordage    : 0 , cover : 0 , adhesive : 0 , flammable : 0 ,
            custom : `` },

        supply : { _isPerishable : false ,
            exhaustion : 0 , hunger : 1 , hypothermia : 0 , wound    : 0 , 
            herb       : 0 , nut    : 0 , root        : 0 , mushroom : 0 , berry : 0 ,
            custom : `` },
    },
},
{   layout: ItemCard , type:Asset.card.item.ship , qty: 5 ,
    name:{ de:"Schiffszwieback", en:"" }, weight: 0 ,
    flavor:{ de:"Jahrelang haltbar, aber auch steinhart", en:"" },
    keyword : {
        clothing : { _isFragile : false ,
            coldProt : 0 , wetProt : 0 , windProt : 0 , storage : 0 , dmgProt : 0 ,
            custom : `` },

        tool : {  _isFragile : false ,
            crafting   : 0 , chopping    : 0 , kindle : 0 , light : 0 ,
            lookout    : 0 , navigation  : 0 ,
            meleeLight : 0 , meleeHeavy  : 0 , ranged : 0 , magic : 0 ,
            custom : `` },

        material : { _isFragile : false ,
            structural : 0 , metallic : 0 , sharp     : 0 , shaft : 0 ,
            cordage    : 0 , cover : 0 , adhesive : 0 , flammable : 0 ,
            custom : `` },

        supply : { _isPerishable : false ,
            exhaustion : 0 , hunger : 1 , hypothermia : 0 , wound    : 0 , 
            herb       : 0 , nut    : 0 , root        : 0 , mushroom : 0 , berry : 0 ,
            custom : `` },
    },
},
{   layout: ItemCard , type:Asset.card.item.ship , qty: 2 ,
    name:{ de:"Kräutertinktur", en:"" }, weight: 0 ,
    flavor:{ de:"Ein fester Bestandteil der europäischen Medizin", en:"" },
    keyword : {
        clothing : { _isFragile : false ,
            coldProt : 0 , wetProt : 0 , windProt : 0 , storage : 0 , dmgProt : 0 ,
            custom : `` },

        tool : {  _isFragile : false ,
            crafting   : 0 , chopping    : 0 , kindle : 0 , light : 0 ,
            lookout    : 0 , navigation  : 0 ,
            meleeLight : 0 , meleeHeavy  : 0 , ranged : 0 , magic : 0 ,
            custom : `` },

        material : { _isFragile : false ,
            structural : 0 , metallic : 0 , sharp     : 0 , shaft : 0 ,
            cordage    : 0 , cover : 0 , adhesive : 0 , flammable : 0 ,
            custom : `` },

        supply : { _isPerishable : false ,
            exhaustion : 0 , hunger : 0 , hypothermia : 0 , wound    : 1 , 
            herb       : 0 , nut    : 0 , root        : 0 , mushroom : 0 , berry : 0 ,
            custom : `` },
    },
},
{   layout: ItemCard , type:Asset.card.item.ship , qty: 3 ,
    name:{ de:"Rum", en:"" }, weight: 0 ,
    flavor:{ de:"Wichtiger Teil der täglichen Verpflegung an Bord", en:"" },
    keyword : {
        clothing : { _isFragile : false ,
            coldProt : 0 , wetProt : 0 , windProt : 0 , storage : 0 , dmgProt : 0 ,
            custom : `` },

        tool : {  _isFragile : false ,
            crafting   : 0 , chopping    : 0 , kindle : 0 , light : 0 ,
            lookout    : 0 , navigation  : 0 ,
            meleeLight : 0 , meleeHeavy  : 0 , ranged : 0 , magic : 0 ,
            custom : `` },

        material : { _isFragile : false ,
            structural : 0 , metallic : 0 , sharp     : 0 , shaft : 0 ,
            cordage    : 0 , cover : 0 , adhesive : 0 , flammable : 0 ,
            custom : `` },

        supply : { _isPerishable : false ,
            exhaustion : 1 , hunger : 1 , hypothermia : 0 , wound    : 0 , 
            herb       : 0 , nut    : 0 , root        : 0 , mushroom : 0 , berry : 0 ,
            custom : `` },
    },
},
{   layout: ItemCard , type:Asset.card.item.ship , qty: 2 ,
    name:{ de:"Tabak", en:"" }, weight: 0 ,
    flavor:{ de:"Fester Bestandteil des Proviants", en:"" },
    keyword : {
        clothing : { _isFragile : false ,
            coldProt : 0 , wetProt : 0 , windProt : 0 , storage : 0 , dmgProt : 0 ,
            custom : `` },

        tool : {  _isFragile : false ,
            crafting   : 0 , chopping    : 0 , kindle : 0 , light : 0 ,
            lookout    : 0 , navigation  : 0 ,
            meleeLight : 0 , meleeHeavy  : 0 , ranged : 0 , magic : 0 ,
            custom : `` },

        material : { _isFragile : false ,
            structural : 0 , metallic : 0 , sharp     : 0 , shaft : 0 ,
            cordage    : 0 , cover : 0 , adhesive : 0 , flammable : 0 ,
            custom : `` },

        supply : { _isPerishable : true ,
            exhaustion : 1 , hunger : 0 , hypothermia : 0 , wound    : 0 , 
            herb       : 0 , nut    : 0 , root        : 0 , mushroom : 0 , berry : 0 ,
            custom : `` },
    },
},









/***** 
F O R A G E
*****/
{   layout: ItemCard , type:Asset.card.item.forage , qty: 8 ,
    name:{ de:"Moos", en:"" }, weight: 0 ,
    flavor:{ de:"", en:"" },
    keyword : {
        clothing : { _isFragile : false ,
            coldProt : 0 , wetProt : 0 , windProt : 0 , storage : 0 , dmgProt : 0 ,
            custom : `` },

        tool : {  _isFragile : false ,
            crafting   : 0 , chopping    : 0 , kindle : 0 , light : 0 ,
            lookout    : 0 , navigation  : 0 ,
            meleeLight : 0 , meleeHeavy  : 0 , ranged : 0 , magic : 0 ,
            custom : `` },

        material : { _isFragile : false ,
            structural : 0 , metallic : 0 , sharp     : 0 , shaft : 0 ,
            cordage    : 0 , cover : 1 , adhesive : 0 , flammable : 1 ,
            custom : `` },

        supply : { _isPerishable : false ,
            exhaustion : 0 , hunger : 1 , hypothermia : 0 , wound    : 0 , 
            herb       : 0 , nut    : 0 , root        : 0 , mushroom : 0 , berry : 0 ,
            custom : `` },
    },
},
{   layout: ItemCard , type:Asset.card.item.forage , qty: 2 ,
    name:{ de:"Wildes Kraut", en:"" }, weight: 0 ,
    flavor:{ de:"", en:"" },
    keyword : {
        clothing : { _isFragile : false ,
            coldProt : 0 , wetProt : 0 , windProt : 0 , storage : 0 , dmgProt : 0 ,
            custom : `` },

        tool : {  _isFragile : false ,
            crafting   : 0 , chopping    : 0 , kindle : 0 , light : 0 ,
            lookout    : 0 , navigation  : 0 ,
            meleeLight : 0 , meleeHeavy  : 0 , ranged : 0 , magic : 0 ,
            custom : `` },

        material : { _isFragile : false ,
            structural : 0 , metallic : 0 , sharp     : 0 , shaft : 0 ,
            cordage    : 0 , cover : 0 , adhesive : 0 , flammable : 0 ,
            custom : `` },

        supply : { _isPerishable : false ,
            exhaustion : 0 , hunger : 0 , hypothermia : 0 , wound    : 0 , 
            herb       : 1 , nut    : 0 , root        : 0 , mushroom : 0 , berry : 0 ,
            custom : `` },
    },
},
{   layout: ItemCard , type:Asset.card.item.forage , qty: 2 ,
    name:{ de:"Wilde Nuss", en:"" }, weight: 0 ,
    flavor:{ de:"", en:"" },
    keyword : {
        clothing : { _isFragile : false ,
            coldProt : 0 , wetProt : 0 , windProt : 0 , storage : 0 , dmgProt : 0 ,
            custom : `` },

        tool : {  _isFragile : false ,
            crafting   : 0 , chopping    : 0 , kindle : 0 , light : 0 ,
            lookout    : 0 , navigation  : 0 ,
            meleeLight : 0 , meleeHeavy  : 0 , ranged : 0 , magic : 0 ,
            custom : `` },

        material : { _isFragile : false ,
            structural : 0 , metallic : 0 , sharp     : 0 , shaft : 0 ,
            cordage    : 0 , cover : 0 , adhesive : 0 , flammable : 0 ,
            custom : `` },

        supply : { _isPerishable : false ,
            exhaustion : 0 , hunger : 0 , hypothermia : 0 , wound    : 0 , 
            herb       : 0 , nut    : 1 , root        : 0 , mushroom : 0 , berry : 0 ,
            custom : `` },
    },
},
{   layout: ItemCard , type:Asset.card.item.forage , qty: 2 ,
    name:{ de:"Wilde Wurzel", en:"" }, weight: 0 ,
    flavor:{ de:"", en:"" },
    keyword : {
        clothing : { _isFragile : false ,
            coldProt : 0 , wetProt : 0 , windProt : 0 , storage : 0 , dmgProt : 0 ,
            custom : `` },

        tool : {  _isFragile : false ,
            crafting   : 0 , chopping    : 0 , kindle : 0 , light : 0 ,
            lookout    : 0 , navigation  : 0 ,
            meleeLight : 0 , meleeHeavy  : 0 , ranged : 0 , magic : 0 ,
            custom : `` },

        material : { _isFragile : false ,
            structural : 0 , metallic : 0 , sharp     : 0 , shaft : 0 ,
            cordage    : 0 , cover : 0 , adhesive : 0 , flammable : 0 ,
            custom : `` },

        supply : { _isPerishable : false ,
            exhaustion : 0 , hunger : 0 , hypothermia : 0 , wound    : 0 , 
            herb       : 0 , nut    : 0 , root        : 1 , mushroom : 0 , berry : 0 ,
            custom : `` },
    },
},
{   layout: ItemCard , type:Asset.card.item.forage , qty: 2 ,
    name:{ de:"Wilder Pilz", en:"" }, weight: 0 ,
    flavor:{ de:"", en:"" },
    keyword : {
        clothing : { _isFragile : false ,
            coldProt : 0 , wetProt : 0 , windProt : 0 , storage : 0 , dmgProt : 0 ,
            custom : `` },

        tool : {  _isFragile : false ,
            crafting   : 0 , chopping    : 0 , kindle : 0 , light : 0 ,
            lookout    : 0 , navigation  : 0 ,
            meleeLight : 0 , meleeHeavy  : 0 , ranged : 0 , magic : 0 ,
            custom : `` },

        material : { _isFragile : false ,
            structural : 0 , metallic : 0 , sharp     : 0 , shaft : 0 ,
            cordage    : 0 , cover : 0 , adhesive : 0 , flammable : 0 ,
            custom : `` },

        supply : { _isPerishable : false ,
            exhaustion : 0 , hunger : 0 , hypothermia : 0 , wound    : 0 , 
            herb       : 0 , nut    : 0 , root        : 0 , mushroom : 1 , berry : 0 ,
            custom : `` },
    },
},
{   layout: ItemCard , type:Asset.card.item.forage , qty: 2 ,
    name:{ de:"Wilde Beere", en:"" }, weight: 0 ,
    flavor:{ de:"", en:"" },
    keyword : {
        clothing : { _isFragile : false ,
            coldProt : 0 , wetProt : 0 , windProt : 0 , storage : 0 , dmgProt : 0 ,
            custom : `` },

        tool : {  _isFragile : false ,
            crafting   : 0 , chopping    : 0 , kindle : 0 , light : 0 ,
            lookout    : 0 , navigation  : 0 ,
            meleeLight : 0 , meleeHeavy  : 0 , ranged : 0 , magic : 0 ,
            custom : `` },

        material : { _isFragile : false ,
            structural : 0 , metallic : 0 , sharp     : 0 , shaft : 0 ,
            cordage    : 0 , cover : 0 , adhesive : 0 , flammable : 0 ,
            custom : `` },

        supply : { _isPerishable : false ,
            exhaustion : 0 , hunger : 0 , hypothermia : 0 , wound    : 0 , 
            herb       : 0 , nut    : 0 , root        : 0 , mushroom : 0 , berry : 1 ,
            custom : `` },
    },
},
{   layout: ItemCard , type:Asset.card.item.forage , qty: 8 ,
    name:{ de:"Stock", en:"" }, weight: 0 ,
    flavor:{ de:"", en:"" },
    keyword : {
        clothing : { _isFragile : false ,
            coldProt : 0 , wetProt : 0 , windProt : 0 , storage : 0 , dmgProt : 0 ,
            custom : `` },

        tool : {  _isFragile : false ,
            crafting   : 0 , chopping    : 0 , kindle : 0 , light : 0 ,
            lookout    : 0 , navigation  : 0 ,
            meleeLight : 0 , meleeHeavy  : 0 , ranged : 0 , magic : 0 ,
            custom : `` },

        material : { _isFragile : false ,
            structural : 0 , metallic : 0 , sharp     : 0 , shaft : 1 ,
            cordage    : 0 , cover : 0 , adhesive : 0 , flammable : 1 ,
            custom : `` },

        supply : { _isPerishable : false ,
            exhaustion : 0 , hunger : 0 , hypothermia : 0 , wound    : 0 , 
            herb       : 0 , nut    : 0 , root        : 0 , mushroom : 0 , berry : 0 ,
            custom : `` },
    },
},
{   layout: ItemCard , type:Asset.card.item.forage , qty: 4 ,
    name:{ de:"Ast", en:"" }, weight: 0 ,
    flavor:{ de:"", en:"" },
    keyword : {
        clothing : { _isFragile : false ,
            coldProt : 0 , wetProt : 0 , windProt : 0 , storage : 0 , dmgProt : 0 ,
            custom : `` },

        tool : {  _isFragile : false ,
            crafting   : 0 , chopping    : 0 , kindle : 0 , light : 0 ,
            lookout    : 0 , navigation  : 0 ,
            meleeLight : 0 , meleeHeavy  : 0 , ranged : 0 , magic : 0 ,
            custom : `` },

        material : { _isFragile : false ,
            structural : 1 , metallic : 0 , sharp     : 0 , shaft : 1 ,
            cordage    : 0 , cover : 0 , adhesive : 0 , flammable : 1 ,
            custom : `` },

        supply : { _isPerishable : false ,
            exhaustion : 0 , hunger : 0 , hypothermia : 0 , wound    : 0 , 
            herb       : 0 , nut    : 0 , root        : 0 , mushroom : 0 , berry : 0 ,
            custom : `` },
    },
},
{   layout: ItemCard , type:Asset.card.item.forage , qty: 3 ,
    name:{ de:"Feuerstein", en:"" }, weight: 0 ,
    flavor:{ de:"", en:"" },
    keyword : {
        clothing : { _isFragile : false ,
            coldProt : 0 , wetProt : 0 , windProt : 0 , storage : 0 , dmgProt : 0 ,
            custom : `` },

        tool : {  _isFragile : false ,
            crafting   : 1 , chopping    : 0 , kindle : 0 , light : 0 ,
            lookout    : 0 , navigation  : 0 ,
            meleeLight : 1 , meleeHeavy  : 0 , ranged : 0 , magic : 0 ,
            custom : `` },

        material : { _isFragile : false ,
            structural : 0 , metallic : 0 , sharp     : 1 , shaft : 0 ,
            cordage    : 0 , cover : 0 , adhesive : 0 , flammable : 0 ,
            custom : `` },

        supply : { _isPerishable : false ,
            exhaustion : 0 , hunger : 0 , hypothermia : 0 , wound    : 0 , 
            herb       : 0 , nut    : 0 , root        : 0 , mushroom : 0 , berry : 0 ,
            custom : `` },
    },
},
{   layout: ItemCard , type:Asset.card.item.forage , qty: 3 ,
    name:{ de:"Ranke", en:"Vine" }, weight: 0 ,
    flavor:{ de:"", en:"" },
    keyword : {
        clothing : { _isFragile : false ,
            coldProt : 0 , wetProt : 0 , windProt : 0 , storage : 0 , dmgProt : 0 ,
            custom : `` },
        tool : {  _isFragile : false ,
            crafting   : 0 , chopping    : 0 , kindle : 0 , light : 0 ,
            lookout    : 0 , navigation  : 0 ,
            meleeLight : 0 , meleeHeavy  : 0 , ranged : 0 , magic : 0 ,
            custom : `` },
        material : { _isFragile : false ,
            structural : 0 , metallic : 0 , sharp     : 0 , shaft : 0 ,
            cordage    : 1 , cover : 0 , adhesive : 0 , flammable : 1 ,
            custom : `` },
        supply : { _isPerishable : false ,
            exhaustion : 0 , hunger : 0 , hypothermia : 0 , wound    : 0 , 
            herb       : 0 , nut    : 0 , root        : 0 , mushroom : 0 , berry : 0 ,
            custom : `` },
    },
},
{   layout: ItemCard , type:Asset.card.item.forage , qty: 3 ,
    name:{ de:"Baumharz", en:"Tree Resin" }, weight: 0 ,
    flavor:{ de:"", en:"" },
    keyword : {
        clothing : { _isFragile : false ,
            coldProt : 0 , wetProt : 0 , windProt : 0 , storage : 0 , dmgProt : 0 ,
            custom : `` },
        tool : {  _isFragile : false ,
            crafting   : 0 , chopping    : 0 , kindle : 0 , light : 0 ,
            lookout    : 0 , navigation  : 0 ,
            meleeLight : 0 , meleeHeavy  : 0 , ranged : 0 , magic : 0 ,
            custom : `` },
        material : { _isFragile : false ,
            structural : 0 , metallic : 0 , sharp     : 0 , shaft : 0 ,
            cordage    : 0 , cover : 1 , adhesive : 1 , flammable : 1 ,
            custom : `` },
        supply : { _isPerishable : false ,
            exhaustion : 0 , hunger : 0 , hypothermia : 0 , wound    : 1 , 
            herb       : 0 , nut    : 0 , root        : 0 , mushroom : 0 , berry : 0 ,
            custom : `` },
    },
},
{   layout: ItemCard , type:Asset.card.item.forage , qty: 3 ,
    name:{ de:"Dichtes Gestrüpp", en:"" }, weight: 0 ,
    flavor:{ de:"", en:"" },
    keyword : {
        clothing : { _isFragile : false ,
            coldProt : 0 , wetProt : 0 , windProt : 0 , storage : 0 , dmgProt : 0 ,
            custom : `` },
        tool : {  _isFragile : true ,
            crafting   : 0 , chopping    : 0 , kindle : 0 , light : 0 ,
            lookout    : 0 , navigation  : 0 ,
            meleeLight : 0 , meleeHeavy  : 0 , ranged : 0 , magic : 0 ,
            custom : `` },
        material : { _isFragile : false ,
            structural : 0 , metallic : 0 , sharp     : 0 , shaft : 0 ,
            cordage    : 0 , cover : 1 , adhesive : 0 , flammable : 1 ,
            custom : `` },
        supply : { _isPerishable : false ,
            exhaustion : 0 , hunger : 0 , hypothermia : 0 , wound    : 0 , 
            herb       : 0 , nut    : 0 , root        : 0 , mushroom : 0 , berry : 0 ,
            custom : `` },
    },
},
{   layout: ItemCard , type:Asset.card.item.forage , qty: 3 ,
    name:{ de:"Zunderpilz", en:"Tinder Fungus" }, weight: 0 ,
    flavor:{ de:"Ein fasrig-filziger Baumpilz", en:"" },
    keyword : {
        clothing : { _isFragile : false ,
            coldProt : 0 , wetProt : 0 , windProt : 0 , storage : 0 , dmgProt : 0 ,
            custom : `` },
        tool : {  _isFragile : false ,
            crafting   : 0 , chopping    : 0 , kindle : 1 , light : 0 ,
            lookout    : 0 , navigation  : 0 ,
            meleeLight : 0 , meleeHeavy  : 0 , ranged : 0 , magic : 0 ,
            custom : `` },
        material : { _isFragile : false ,
            structural : 0 , metallic : 0 , sharp     : 0 , shaft : 0 ,
            cordage    : 1 , cover : 0 , adhesive : 0 , flammable : 1 ,
            custom : `` },
        supply : { _isPerishable : false ,
            exhaustion : 0 , hunger : 0 , hypothermia : 0 , wound    : 1 , 
            herb       : 0 , nut    : 0 , root        : 0 , mushroom : 0 , berry : 0 ,
            custom : `` },
    }
},
/***** 
H U N T
*****/
{   layout: ItemCard , type:Asset.card.item.hunt , qty: 16 ,
    name:{ de:"Fleisch", en:"" }, weight: 0 ,
    flavor:{ de:"Roh schlecht verträglich", en:"" },
    keyword : {
        clothing : { _isFragile : false ,
            coldProt : 0 , wetProt : 0 , windProt : 0 , storage : 0 , dmgProt : 0 ,
            custom : `` },

        tool : {  _isFragile : false ,
            crafting   : 0 , chopping    : 0 , kindle : 0 , light : 0 ,
            lookout    : 0 , navigation  : 0 ,
            meleeLight : 0 , meleeHeavy  : 0 , ranged : 0 , magic : 0 ,
            custom : `` },

        material : { _isFragile : false ,
            structural : 0 , metallic : 0 , sharp     : 0 , shaft : 0 ,
            cordage    : 0 , cover : 0 , adhesive : 0 , flammable : 0 ,
            custom : `` },

        supply : { _isPerishable : true ,
            exhaustion : 0 , hunger : 1 , hypothermia : 0 , wound    : 0 , 
            herb       : 0 , nut    : 0 , root        : 0 , mushroom : 0 , berry : 0 ,
            custom : `` },
    },
},
{   layout: ItemCard , type:Asset.card.item.hunt , qty: 3 ,
    name:{ de:"Knochen", en:"" }, weight: 0 ,
    flavor:{ de:"Hart genug für primitives Werkzeug", en:"" },
    keyword : {
        clothing : { _isFragile : false ,
            coldProt : 0 , wetProt : 0 , windProt : 0 , storage : 0 , dmgProt : 0 ,
            custom : `` },

        tool : {  _isFragile : false ,
            crafting   : 1 , chopping    : 0 , kindle : 0 , light : 0 ,
            lookout    : 0 , navigation  : 0 ,
            meleeLight : 1 , meleeHeavy  : 0 , ranged : 0 , magic : 0 ,
            custom : `` },

        material : { _isFragile : false ,
            structural : 0 , metallic : 0 , sharp     : 1 , shaft : 1 ,
            cordage    : 0 , cover : 0 , adhesive : 0 , flammable : 0 ,
            custom : `` },

        supply : { _isPerishable : false ,
            exhaustion : 0 , hunger : 0 , hypothermia : 0 , wound    : 0 , 
            herb       : 0 , nut    : 0 , root        : 0 , mushroom : 0 , berry : 0 ,
            custom : `` },
    },
},
{   layout: ItemCard , type:Asset.card.item.hunt , qty: 3 ,
    name:{ de:"Leder", en:"" }, weight: 0 ,
    flavor:{ de:"Zäh und widerstandsfähig", en:"" },
    keyword : {
        clothing : { _isFragile : false ,
            coldProt : 0 , wetProt : 0 , windProt : 0 , storage : 0 , dmgProt : 1 ,
            custom : `` },

        tool : {  _isFragile : false ,
            crafting   : 0 , chopping    : 0 , kindle : 0 , light : 0 ,
            lookout    : 0 , navigation  : 0 ,
            meleeLight : 0 , meleeHeavy  : 0 , ranged : 0 , magic : 0 ,
            custom : `` },

        material : { _isFragile : false ,
            structural : 0 , metallic : 0 , sharp     : 0 , shaft : 0 ,
            cordage    : 1 , cover : 1 , adhesive : 0 , flammable : 0 ,
            custom : `` },

        supply : { _isPerishable : false ,
            exhaustion : 0 , hunger : 0 , hypothermia : 0 , wound    : 0 , 
            herb       : 0 , nut    : 0 , root        : 0 , mushroom : 0 , berry : 0 ,
            custom : `` },
    },
},
{   layout: ItemCard , type:Asset.card.item.hunt , qty: 3 ,
    name:{ de:"Fell", en:"" }, weight: 0 ,
    flavor:{ de:"Hat vorher ein Tier warm gehalten, warum also nicht dich", en:"" },
    keyword : {
        clothing : { _isFragile : true ,
            coldProt : 1 , wetProt : 0 , windProt : 1 , storage : 0 , dmgProt : 0 ,
            custom : `` },

        tool : {  _isFragile : false ,
            crafting   : 0 , chopping    : 0 , kindle : 0 , light : 0 ,
            lookout    : 0 , navigation  : 0 ,
            meleeLight : 0 , meleeHeavy  : 0 , ranged : 0 , magic : 0 ,
            custom : `` },

        material : { _isFragile : false ,
            structural : 0 , metallic : 0 , sharp     : 0 , shaft : 0 ,
            cordage    : 1 , cover : 1 , adhesive : 0 , flammable : 1 ,
            custom : `` },

        supply : { _isPerishable : false ,
            exhaustion : 0 , hunger : 0 , hypothermia : 0 , wound    : 0 , 
            herb       : 0 , nut    : 0 , root        : 0 , mushroom : 0 , berry : 0 ,
            custom : `` },
    },
},
{   layout: ItemCard , type:Asset.card.item.hunt , qty: 3 ,
    name:{ de:"Fett", en:"" }, weight: 0 ,
    flavor:{ de:"Energiereich und brennt hervorragend", en:"" },
    keyword : {
        clothing : { _isFragile : false ,
            coldProt : 0 , wetProt : 0 , windProt : 0 , storage : 0 , dmgProt : 0 ,
            custom : `` },

        tool : {  _isFragile : false ,
            crafting   : 0 , chopping    : 0 , kindle : 0 , light : 0 ,
            lookout    : 0 , navigation  : 0 ,
            meleeLight : 0 , meleeHeavy  : 0 , ranged : 0 , magic : 0 ,
            custom : `` },

        material : { _isFragile : false ,
            structural : 0 , metallic : 0 , sharp     : 0 , shaft : 0 ,
            cordage    : 0 , cover : 0 , adhesive : 1 , flammable : 1 ,
            custom : `` },

        supply : { _isPerishable : true ,
            exhaustion : 0 , hunger : 1 , hypothermia : 0 , wound    : 0 , 
            herb       : 0 , nut    : 0 , root        : 0 , mushroom : 0 , berry : 0 ,
            custom : `` },
    },
},
{   layout: ItemCard , type:Asset.card.item.hunt , qty: 3 ,
    name:{ de:"Sehnen", en:"" }, weight: 0 ,
    flavor:{ de:"Viel robuster als pflanzliche Fasern", en:"" },
    keyword : {
        clothing : { _isFragile : false ,
            coldProt : 0 , wetProt : 0 , windProt : 0 , storage : 0 , dmgProt : 0 ,
            custom : `` },

        tool : {  _isFragile : false ,
            crafting   : 0 , chopping    : 0 , kindle : 0 , light : 0 ,
            lookout    : 0 , navigation  : 0 ,
            meleeLight : 0 , meleeHeavy  : 0 , ranged : 0 , magic : 0 ,
            custom : `` },

        material : { _isFragile : false ,
            structural : 0 , metallic : 0 , sharp     : 0 , shaft : 0 ,
            cordage    : 1 , cover : 0 , adhesive : 0 , flammable : 1 ,
            custom : `` },

        supply : { _isPerishable : true ,
            exhaustion : 0 , hunger : 0 , hypothermia : 0 , wound    : 0 , 
            herb       : 0 , nut    : 0 , root        : 0 , mushroom : 0 , berry : 0 ,
            custom : `` },
    },
},
/***** 
W O O D
*****/
{   layout: ItemCard , type:Asset.card.item.wood , qty: 16 ,
    name:{ de:"Scheit", en:"" }, weight: 1 ,
    flavor:{ de:"Gutes Brennholz und Baumaterial", en:"" },
    keyword : {
        clothing : { _isFragile : false ,
            coldProt : 0 , wetProt : 0 , windProt : 0 , storage : 0 , dmgProt : 0 ,
            custom : `` },

        tool : {  _isFragile : false ,
            crafting   : 0 , chopping    : 0 , kindle : 0 , light : 0 ,
            lookout    : 0 , navigation  : 0 ,
            meleeLight : 0 , meleeHeavy  : 0 , ranged : 0 , magic : 0 ,
            custom : `` },

        material : { _isFragile : false ,
            structural : 1 , metallic : 0 , sharp     : 0 , shaft : 0 ,
            cordage    : 0 , cover : 0 , adhesive : 0 , flammable : 1 ,
            custom : `` },

        supply : { _isPerishable : false ,
            exhaustion : 0 , hunger : 0 , hypothermia : 0 , wound    : 0 , 
            herb       : 0 , nut    : 0 , root        : 0 , mushroom : 0 , berry : 0 ,
            custom : `` },
    },
},
{   layout: ItemCard , type:Asset.card.item.wood , qty: 3 ,
    name:{ de:"Ast", en:"" }, weight: 0 ,
    flavor:{ de:"Vielseitig einsetzbar", en:"" },
    keyword : {
        clothing : { _isFragile : false ,
            coldProt : 0 , wetProt : 0 , windProt : 0 , storage : 0 , dmgProt : 0 ,
            custom : `` },

        tool : {  _isFragile : false ,
            crafting   : 0 , chopping    : 0 , kindle : 0 , light : 0 ,
            lookout    : 0 , navigation  : 0 ,
            meleeLight : 0 , meleeHeavy  : 0 , ranged : 0 , magic : 0 ,
            custom : `` },

        material : { _isFragile : false ,
            structural : 0 , metallic : 0 , sharp     : 0 , shaft : 1 ,
            cordage    : 0 , cover : 0 , adhesive : 0 , flammable : 1 ,
            custom : `` },

        supply : { _isPerishable : false ,
            exhaustion : 0 , hunger : 0 , hypothermia : 0 , wound    : 0 , 
            herb       : 0 , nut    : 0 , root        : 0 , mushroom : 0 , berry : 0 ,
            custom : `` },
    },
},
{   layout: ItemCard , type:Asset.card.item.wood , qty: 3 ,
    name:{ de:"Baumrinde", en:"Tree Bark" }, weight: 0 ,
    flavor:{ de:"Kann als Dachmaterial oder Medizin genutzt werden", en:"Can be used as roofing or medicine." },
    keyword : {
        clothing : { _isFragile : false ,
            coldProt : 0 , wetProt : 0 , windProt : 0 , storage : 0 , dmgProt : 0 ,
            custom : `` },
        tool : {  _isFragile : false ,
            crafting   : 0 , chopping    : 0 , kindle : 0 , light : 0 ,
            lookout    : 0 , navigation  : 0 ,
            meleeLight : 0 , meleeHeavy  : 0 , ranged : 0 , magic : 0 ,
            custom : `` },
        material : { _isFragile : true ,
            structural : 0 , metallic : 0 , sharp     : 0 , shaft : 0 ,
            cordage    : 1 , cover : 1 , adhesive : 0 , flammable : 1 ,
            custom : `` },
        supply : { _isPerishable : false ,
            exhaustion : 0 , hunger : 0 , hypothermia : 0 , wound    : 1 ,
            herb       : 0 , nut    : 0 , root        : 0 , mushroom : 0 , berry : 0 ,
            custom : `` },
    },
},
{   layout: ItemCard , type:Asset.card.item.wood , qty: 3 ,
    name:{ de:"Baumharz", en:"Tree Resin" }, weight: 0 ,
    flavor:{ de:"", en:"" },
    keyword : {
        clothing : { _isFragile : false ,
            coldProt : 0 , wetProt : 0 , windProt : 0 , storage : 0 , dmgProt : 0 ,
            custom : `` },
        tool : {  _isFragile : false ,
            crafting   : 0 , chopping    : 0 , kindle : 0 , light : 0 ,
            lookout    : 0 , navigation  : 0 ,
            meleeLight : 0 , meleeHeavy  : 0 , ranged : 0 , magic : 0 ,
            custom : `` },
        material : { _isFragile : false ,
            structural : 0 , metallic : 0 , sharp     : 0 , shaft : 0 ,
            cordage    : 0 , cover : 1 , adhesive : 1 , flammable : 1 ,
            custom : `` },
        supply : { _isPerishable : false ,
            exhaustion : 0 , hunger : 0 , hypothermia : 0 , wound    : 1 , 
            herb       : 0 , nut    : 0 , root        : 0 , mushroom : 0 , berry : 0 ,
            custom : `` },
    },
},


/***** 
C R A F T
*****/
{   layout: ItemCard , type:Asset.card.item.craft , qty: 3 ,
    name:{ de:"Messer", en:"" }, weight: 0 ,
    flavor:{ de:"ein kleines, kurzes improvisiertes Messer", en:"" },
    keyword : {
        craft : { _isComplex : true ,
            clothing : {    coldProt   : 0 , wetProt     : 0 , windProt    : 0 , storage   : 0 , dmgProt : 0 },
            tool     : {    crafting   : 0 , chopping    : 0 , kindle      : 0 , light     : 0 ,
                            lookout    : 0 , navigation  : 0 , 
                            meleeLight : 0 , meleeHeavy  : 0 , ranged      : 0 , magic     : 0 },
            material : {    structural : 0 , metallic    : 0 , sharp       : 1 , shaft     : 0 ,
                            cordage    : 1 , cover       : 0 , adhesive    : 0 , flammable : 0 },
            supply   : {    exhaustion : 0 , hunger      : 0 , hypothermia : 0 , wound     : 0 , 
                            herb       : 0 , nut         : 0 , root        : 0 , mushroom  : 0 , berry   : 0 },
            custom : `` },

        clothing : { _isFragile : false ,
            coldProt : 0 , wetProt : 0 , windProt : 0 , storage : 0 , dmgProt : 0 ,
            custom : `` },

        tool : {  _isFragile : false ,
            crafting   : 1 , chopping    : 0 , kindle : 0 , light : 0 ,
            lookout    : 0 , navigation  : 0 ,
            meleeLight : 1 , meleeHeavy  : 0 , ranged : 0 , magic : 0 ,
            custom : `` },

        material : { _isFragile : false ,
            structural : 0 , metallic : 0 , sharp     : 1 , shaft : 0 ,
            cordage    : 0 , cover : 0 , adhesive : 0 , flammable : 0 ,
            custom : `` },

        supply : { _isPerishable : false ,
            exhaustion : 0 , hunger : 0 , hypothermia : 0 , wound    : 0 , 
            herb       : 0 , nut    : 0 , root        : 0 , mushroom : 0 , berry : 0 ,
            custom : `` },
    },
},
{   layout: ItemCard , type:Asset.card.item.craft , qty: 3 ,
    name:{ de:"Falle", en:"" }, weight: 0 ,
    flavor:{ de:"", en:"" },
    keyword : {
        craft : { _isComplex : true ,
            clothing : {    coldProt   : 0 , wetProt     : 0 , windProt    : 0 , storage   : 0 , dmgProt : 0 },
            tool     : {    crafting   : 0 , chopping    : 0 , kindle      : 0 , light     : 0 ,
                            lookout    : 0 , navigation  : 0 , 
                            meleeLight : 0 , meleeHeavy  : 0 , ranged      : 0 , magic     : 0 },
            material : {    structural : 0 , metallic    : 0 , sharp       : 1 , shaft     : 1 ,
                            cordage    : 1 , cover       : 0 , adhesive    : 0 , flammable : 0 },
            supply   : {    exhaustion : 0 , hunger      : 0 , hypothermia : 0 , wound     : 0 , 
                            herb       : 0 , nut         : 0 , root        : 0 , mushroom  : 0 , berry   : 0 },
            custom : `` },

        clothing : { _isFragile : false ,
            coldProt : 0 , wetProt : 0 , windProt : 0 , storage : 0 , dmgProt : 0 ,
            custom : `` },

        tool : {  _isFragile : true ,
            crafting   : 0 , chopping    : 0 , kindle : 0 , light : 0 ,
            lookout    : 0 , navigation  : 0 ,
            meleeLight : 0 , meleeHeavy  : 0 , ranged : 0 , magic : 0 ,
            custom : `+2 ${Asset.tile.action.hunting.icon} pro Coin (max 6)` },

        material : { _isFragile : false ,
            structural : 0 , metallic : 0 , sharp     : 1 , shaft : 1 ,
            cordage    : 0 , cover : 0 , adhesive : 0 , flammable : 0 ,
            custom : `` },

        supply : { _isPerishable : false ,
            exhaustion : 0 , hunger : 0 , hypothermia : 0 , wound    : 0 , 
            herb       : 0 , nut    : 0 , root        : 0 , mushroom : 0 , berry : 0 ,
            custom : `` },
    },
},
{   layout: ItemCard , type:Asset.card.item.craft , qty: 3 ,
    name:{ de:"improvisierte Axt", en:"" }, weight: 1 ,
    flavor:{ de:"", en:"" },
    keyword : {
        craft : { _isComplex : true ,
            clothing : {    coldProt   : 0 , wetProt     : 0 , windProt    : 0 , storage   : 0 , dmgProt : 0 },
            tool     : {    crafting   : 0 , chopping    : 0 , kindle      : 0 , light     : 0 ,
                            lookout    : 0 , navigation  : 0 , 
                            meleeLight : 0 , meleeHeavy  : 0 , ranged      : 0 , magic     : 0 },
            material : {    structural : 0 , metallic    : 0 , sharp       : 1 , shaft     : 1 ,
                            cordage    : 0 , cover       : 0 , adhesive    : 0 , flammable : 1 },
            supply   : {    exhaustion : 0 , hunger      : 0 , hypothermia : 0 , wound     : 0 , 
                            herb       : 0 , nut         : 0 , root        : 0 , mushroom  : 0 , berry   : 0 },
            custom : `${Asset.keyword.material.cordage.icon}/${Asset.keyword.material.adhesive.icon}` },

        clothing : { _isFragile : false ,
            coldProt : 0 , wetProt : 0 , windProt : 0 , storage : 0 , dmgProt : 0 ,
            custom : `` },

        tool : {  _isFragile : false ,
            crafting   : 0 , chopping    : 1 , kindle : 0 , light : 0 ,
            lookout    : 0 , navigation  : 0 ,
            meleeLight : 0 , meleeHeavy  : 1 , ranged : 0 , magic : 0 ,
            custom : `` },

        material : { _isFragile : false ,
            structural : 0 , metallic : 0 , sharp     : 1 , shaft : 1 ,
            cordage    : 0 , cover : 0 , adhesive : 0 , flammable : 1 ,
            custom : `` },

        supply : { _isPerishable : false ,
            exhaustion : 0 , hunger : 0 , hypothermia : 0 , wound    : 0 , 
            herb       : 0 , nut    : 0 , root        : 0 , mushroom : 0 , berry : 0 ,
            custom : `` },
    },
},
{   layout: ItemCard , type:Asset.card.item.craft , qty: 3 ,
    name:{ de:"Pflanzenextrakt", en:"" }, weight: 0 ,
    flavor:{ de:"", en:"" },
    keyword : {
        craft : { _isComplex : false ,
            clothing : {    coldProt   : 0 , wetProt     : 0 , windProt    : 0 , storage   : 0 , dmgProt : 0 },
            tool     : {    crafting   : 0 , chopping    : 0 , kindle      : 0 , light     : 0 ,
                            lookout    : 0 , navigation  : 0 , 
                            meleeLight : 0 , meleeHeavy  : 0 , ranged      : 0 , magic     : 0 },
            material : {    structural : 0 , metallic    : 0 , sharp       : 0 , shaft     : 0 ,
                            cordage    : 0 , cover       : 0 , adhesive    : 0 , flammable : 0 },
            supply   : {    exhaustion : 0 , hunger      : 0 , hypothermia : 0 , wound     : 0 , 
                            herb       : 0 , nut         : 0 , root        : 0 , mushroom  : 0 , berry   : 0 },
            custom : `2x ${Asset.keyword.supply.herb.icon}/${Asset.keyword.supply.nut.icon}/${Asset.keyword.supply.root.icon}/${Asset.keyword.supply.mushroom.icon}/${Asset.keyword.supply.berry.icon}` },

        clothing : { _isFragile : false ,
            coldProt : 0 , wetProt : 0 , windProt : 0 , storage : 0 , dmgProt : 0 ,
            custom : `` },

        tool : {  _isFragile : false ,
            crafting   : 0 , chopping    : 0 , kindle : 0 , light : 0 ,
            lookout    : 0 , navigation  : 0 ,
            meleeLight : 0 , meleeHeavy  : 0 , ranged : 0 , magic : 0 ,
            custom : `` },

        material : { _isFragile : false ,
            structural : 0 , metallic : 0 , sharp     : 0 , shaft : 0 ,
            cordage    : 0 , cover : 0 , adhesive : 0 , flammable : 0 ,
            custom : `` },

        supply : { _isPerishable : false ,
            exhaustion : 0 , hunger : 0 , hypothermia : 0 , wound    : 1 , 
            herb       : 0 , nut    : 0 , root        : 0 , mushroom : 0 , berry : 0 ,
            custom : `` },
    },
},
{   layout: ItemCard , type:Asset.card.item.craft , qty: 3 ,
    name:{ de:"Brett", en:"" }, weight: 0 ,
    flavor:{ de:"", en:"" },
    keyword : {
        craft : { _isComplex : false ,
            clothing : {    coldProt   : 0 , wetProt     : 0 , windProt    : 0 , storage   : 0 , dmgProt : 0 },
            tool     : {    crafting   : 0 , chopping    : 0 , kindle      : 0 , light     : 0 ,
                            lookout    : 0 , navigation  : 0 , 
                            meleeLight : 0 , meleeHeavy  : 0 , ranged      : 0 , magic     : 0 },
            material : {    structural : 0 , metallic    : 0 , sharp       : 0 , shaft     : 2 ,
                            cordage    : 0 , cover       : 0 , adhesive    : 0 , flammable : 0 },
            supply   : {    exhaustion : 0 , hunger      : 0 , hypothermia : 0 , wound     : 0 , 
                            herb       : 0 , nut         : 0 , root        : 0 , mushroom  : 0 , berry   : 0 },
            custom : `` },

        clothing : { _isFragile : false ,
            coldProt : 0 , wetProt : 0 , windProt : 0 , storage : 0 , dmgProt : 0 ,
            custom : `` },

        tool : {  _isFragile : false ,
            crafting   : 0 , chopping    : 0 , kindle : 0 , light : 0 ,
            lookout    : 0 , navigation  : 0 ,
            meleeLight : 0 , meleeHeavy  : 0 , ranged : 0 , magic : 0 ,
            custom : `` },

        material : { _isFragile : false ,
            structural : 1 , metallic : 0 , sharp     : 0 , shaft : 0 ,
            cordage    : 0 , cover : 0 , adhesive : 0 , flammable : 1 ,
            custom : `` },

        supply : { _isPerishable : false ,
            exhaustion : 0 , hunger : 0 , hypothermia : 0 , wound    : 0 , 
            herb       : 0 , nut    : 0 , root        : 0 , mushroom : 0 , berry : 0 ,
            custom : `` },
    },
},
{   layout: ItemCard , type:Asset.card.item.craft , qty: 3 ,
    name:{ de:"Leinenhemd", en:"" }, weight: 0 ,
    flavor:{ de:"", en:"" },
    keyword : {
        craft : { _isComplex : false ,
            clothing : {    coldProt   : 0 , wetProt     : 0 , windProt    : 0 , storage   : 0 , dmgProt : 0 },
            tool     : {    crafting   : 0 , chopping    : 0 , kindle      : 0 , light     : 0 ,
                            lookout    : 0 , navigation  : 0 , 
                            meleeLight : 0 , meleeHeavy  : 0 , ranged      : 0 , magic     : 0 },
            material : {    structural : 0 , metallic    : 0 , sharp       : 0 , shaft     : 0 ,
                            cordage    : 2 , cover       : 1 , adhesive    : 0 , flammable : 0 },
            supply   : {    exhaustion : 0 , hunger      : 0 , hypothermia : 0 , wound     : 0 , 
                            herb       : 0 , nut         : 0 , root        : 0 , mushroom  : 0 , berry   : 0 },
            custom : `` },

        clothing : { _isFragile : false ,
            coldProt : 1 , wetProt : 0 , windProt : 0 , storage : 0 , dmgProt : 0 ,
            custom : `` },

        tool : {  _isFragile : false ,
            crafting   : 0 , chopping    : 0 , kindle : 0 , light : 0 ,
            lookout    : 0 , navigation  : 0 ,
            meleeLight : 0 , meleeHeavy  : 0 , ranged : 0 , magic : 0 ,
            custom : `` },

        material : { _isFragile : false ,
            structural : 0 , metallic : 0 , sharp     : 0 , shaft : 0 ,
            cordage    : 1 , cover : 0 , adhesive : 0 , flammable : 1 ,
            custom : `` },

        supply : { _isPerishable : false ,
            exhaustion : 0 , hunger : 0 , hypothermia : 0 , wound    : 0 , 
            herb       : 0 , nut    : 0 , root        : 0 , mushroom : 0 , berry : 0 ,
            custom : `` },
    },
},
{   layout: ItemCard , type:Asset.card.item.craft , qty: 3 ,
    name:{ de:"Beutel", en:"" }, weight: 0 ,
    flavor:{ de:"", en:"" },
    keyword : {
        craft : { _isComplex : false ,
            clothing : {    coldProt   : 0 , wetProt     : 0 , windProt    : 0 , storage   : 0 , dmgProt : 0 },
            tool     : {    crafting   : 0 , chopping    : 0 , kindle      : 0 , light     : 0 ,
                            lookout    : 0 , navigation  : 0 , 
                            meleeLight : 0 , meleeHeavy  : 0 , ranged      : 0 , magic     : 0 },
            material : {    structural : 0 , metallic    : 0 , sharp       : 0 , shaft     : 0 ,
                            cordage    : 1 , cover       : 1 , adhesive    : 0 , flammable : 0 },
            supply   : {    exhaustion : 0 , hunger      : 0 , hypothermia : 0 , wound     : 0 , 
                            herb       : 0 , nut         : 0 , root        : 0 , mushroom  : 0 , berry   : 0 },
            custom : `` },

        clothing : { _isFragile : false ,
            coldProt : 0 , wetProt : 0 , windProt : 0 , storage : 1 , dmgProt : 0 ,
            custom : `` },

        tool : {  _isFragile : false ,
            crafting   : 0 , chopping    : 0 , kindle : 0 , light : 0 ,
            lookout    : 0 , navigation  : 0 ,
            meleeLight : 0 , meleeHeavy  : 0 , ranged : 0 , magic : 0 ,
            custom : `` },

        material : { _isFragile : false ,
            structural : 0 , metallic : 0 , sharp     : 0 , shaft : 0 ,
            cordage    : 1 , cover : 0 , adhesive : 0 , flammable : 1 ,
            custom : `` },

        supply : { _isPerishable : false ,
            exhaustion : 0 , hunger : 0 , hypothermia : 0 , wound    : 0 , 
            herb       : 0 , nut    : 0 , root        : 0 , mushroom : 0 , berry : 0 ,
            custom : `` },
    },
},
{   layout: ItemCard , type:Asset.card.item.craft , qty: 3 ,
    name:{ de:"Naturfaden", en:"" }, weight: 0 ,
    flavor:{ de:"", en:"" },
    keyword : {
        craft : { _isComplex : true ,
            clothing : {    coldProt   : 0 , wetProt     : 0 , windProt    : 0 , storage   : 0 , dmgProt : 0 },
            tool     : {    crafting   : 0 , chopping    : 0 , kindle      : 0 , light     : 0 ,
                            lookout    : 0 , navigation  : 0 , 
                            meleeLight : 0 , meleeHeavy  : 0 , ranged      : 0 , magic     : 0 },
            material : {    structural : 0 , metallic    : 0 , sharp       : 0 , shaft     : 0 ,
                            cordage    : 0 , cover       : 0 , adhesive    : 0 , flammable : 0 },
            supply   : {    exhaustion : 0 , hunger      : 0 , hypothermia : 0 , wound     : 0 , 
                            herb       : 0 , nut         : 0 , root        : 0 , mushroom  : 0 , berry   : 0 },
            custom : ` ` },

        clothing : { _isFragile : false ,
            coldProt : 0 , wetProt : 0 , windProt : 0 , storage : 0 , dmgProt : 0 ,
            custom : `` },

        tool : {  _isFragile : false ,
            crafting   : 0 , chopping    : 0 , kindle : 0 , light : 0 ,
            lookout    : 0 , navigation  : 0 ,
            meleeLight : 0 , meleeHeavy  : 0 , ranged : 0 , magic : 0 ,
            custom : `` },

        material : { _isFragile : false ,
            structural : 0 , metallic : 0 , sharp     : 0 , shaft : 0 ,
            cordage    : 1 , cover : 0 , adhesive : 0 , flammable : 1 ,
            custom : `` },

        supply : { _isPerishable : false ,
            exhaustion : 0 , hunger : 0 , hypothermia : 0 , wound    : 0 , 
            herb       : 0 , nut    : 0 , root        : 0 , mushroom : 0 , berry : 0 ,
            custom : `` },
    },
},
{   layout: ItemCard , type:Asset.card.item.craft , qty: 3 ,
    name:{ de:"Bandage", en:"" }, weight: 0 ,
    flavor:{ de:"", en:"" },
    keyword : {
        craft : { _isComplex : true ,
            clothing : {    coldProt   : 0 , wetProt     : 0 , windProt    : 0 , storage   : 0 , dmgProt : 0 },
            tool     : {    crafting   : 0 , chopping    : 0 , kindle      : 0 , light     : 0 ,
                            lookout    : 0 , navigation  : 0 , 
                            meleeLight : 0 , meleeHeavy  : 0 , ranged      : 0 , magic     : 0 },
            material : {    structural : 0 , metallic    : 0 , sharp       : 0 , shaft     : 0 ,
                            cordage    : 1 , cover       : 1 , adhesive    : 0 , flammable : 0 },
            supply   : {    exhaustion : 0 , hunger      : 0 , hypothermia : 0 , wound     : 0 , 
                            herb       : 0 , nut         : 0 , root        : 0 , mushroom  : 0 , berry   : 0 },
            custom : `` },

        clothing : { _isFragile : false ,
            coldProt : 0 , wetProt : 0 , windProt : 0 , storage : 0 , dmgProt : 0 ,
            custom : `` },

        tool : {  _isFragile : false ,
            crafting   : 0 , chopping    : 0 , kindle : 0 , light : 0 ,
            lookout    : 0 , navigation  : 0 ,
            meleeLight : 0 , meleeHeavy  : 0 , ranged : 0 , magic : 0 ,
            custom : `` },

        material : { _isFragile : false ,
            structural : 0 , metallic : 0 , sharp     : 0 , shaft : 0 ,
            cordage    : 1 , cover : 0 , adhesive : 0 , flammable : 1 ,
            custom : `` },

        supply : { _isPerishable : false ,
            exhaustion : 0 , hunger : 0 , hypothermia : 0 , wound    : 1 , 
            herb       : 0 , nut    : 0 , root        : 0 , mushroom : 0 , berry : 0 ,
            custom : `` },
    },
},



/***** 
S H E L T E R
*****/
{   layout: ItemCard , type:Asset.card.item.tent , qty: 3 ,
    name:{ de:"Zelt", en:"" }, weight: 5 ,
    flavor:{ de:"", en:"" },
    keyword : {
        craft : { _isComplex : true ,
            clothing : {    coldProt   : 0 , wetProt     : 0 , windProt    : 0 , storage   : 0 , dmgProt : 0 },
            tool     : {    crafting   : 0 , chopping    : 0 , kindle      : 0 , light     : 0 ,
                            lookout    : 0 , navigation  : 0 , 
                            meleeLight : 0 , meleeHeavy  : 0 , ranged      : 0 , magic     : 0 },
            material : {    structural : 0 , metallic    : 0 , sharp       : 0 , shaft     : 2 ,
                            cordage    : 1 , cover       : 1 , adhesive    : 0 , flammable : 0 },
            supply   : {    exhaustion : 0 , hunger      : 0 , hypothermia : 0 , wound     : 0 , 
                            herb       : 0 , nut         : 0 , root        : 0 , mushroom  : 0 , berry   : 0 },
            custom : `` },

        clothing : { _isFragile : false ,
            coldProt : 0 , wetProt : 2 , windProt : 1 , storage : 0 , dmgProt : 0 ,
            custom : `` },

        tool : {  _isFragile : false ,
            crafting   : 0 , chopping    : 0 , kindle : 0 , light : 0 ,
            lookout    : 0 , navigation  : 0 ,
            meleeLight : 0 , meleeHeavy  : 0 , ranged : 0 , magic : 0 ,
            custom : `` },

        material : { _isFragile : false ,
            structural : 0 , metallic : 0 , sharp     : 0 , shaft : 0 ,
            cordage    : 0 , cover : 0 , adhesive : 0 , flammable : 0 ,
            custom : `` },

        supply : { _isPerishable : false ,
            exhaustion : 0 , hunger : 0 , hypothermia : 0 , wound    : 0 , 
            herb       : 0 , nut    : 0 , root        : 0 , mushroom : 0 , berry : 0 ,
            custom : `` },
    },
},
{   layout: ItemCard , type:Asset.card.item.hut , qty: 3 ,
    name:{ de:"Unterschlupf", en:"" }, weight: 5 ,
    flavor:{ de:"", en:"" },
    keyword : {
        craft : { _isComplex : true ,
            clothing : {    coldProt   : 0 , wetProt     : 0 , windProt    : 0 , storage   : 0 , dmgProt : 0 },
            tool     : {    crafting   : 0 , chopping    : 0 , kindle      : 0 , light     : 0 ,
                            lookout    : 0 , navigation  : 0 , 
                            meleeLight : 0 , meleeHeavy  : 0 , ranged      : 0 , magic     : 0 },
            material : {    structural : 1 , metallic    : 0 , sharp       : 0 , shaft     : 1 ,
                            cordage    : 1 , cover       : 1 , adhesive    : 0 , flammable : 0 },
            supply   : {    exhaustion : 0 , hunger      : 0 , hypothermia : 0 , wound     : 0 , 
                            herb       : 0 , nut         : 0 , root        : 0 , mushroom  : 0 , berry   : 0 },
            custom : `` },

        clothing : { _isFragile : false ,
            coldProt : 1 , wetProt : 3 , windProt : 2 , storage : 0 , dmgProt : 0 ,
            custom : `` },

        tool : {  _isFragile : false ,
            crafting   : 0 , chopping    : 0 , kindle : 0 , light : 0 ,
            lookout    : 0 , navigation  : 0 ,
            meleeLight : 0 , meleeHeavy  : 0 , ranged : 0 , magic : 0 ,
            custom : `` },

        material : { _isFragile : false ,
            structural : 0 , metallic : 0 , sharp     : 0 , shaft : 0 ,
            cordage    : 0 , cover : 0 , adhesive : 0 , flammable : 0 ,
            custom : `` },

        supply : { _isPerishable : false ,
            exhaustion : 0 , hunger : 0 , hypothermia : 0 , wound    : 0 , 
            herb       : 0 , nut    : 0 , root        : 0 , mushroom : 0 , berry : 0 ,
            custom : `` },
    },
},
{   layout: ItemCard , type:Asset.card.item.house , qty: 3 ,
    name:{ de:"Hütte", en:"" }, weight: 5 ,
    flavor:{ de:"", en:"" },
    keyword : {
        craft : { _isComplex : true ,
            clothing : {    coldProt   : 0 , wetProt     : 0 , windProt    : 0 , storage   : 0 , dmgProt : 0 },
            tool     : {    crafting   : 0 , chopping    : 0 , kindle      : 0 , light     : 0 ,
                            lookout    : 0 , navigation  : 0 , 
                            meleeLight : 0 , meleeHeavy  : 0 , ranged      : 0 , magic     : 0 },
            material : {    structural : 1 , metallic    : 0 , sharp       : 0 , shaft     : 0 ,
                            cordage    : 1 , cover       : 1 , adhesive    : 0 , flammable : 0 },
            supply   : {    exhaustion : 0 , hunger      : 0 , hypothermia : 0 , wound     : 0 , 
                            herb       : 0 , nut         : 0 , root        : 0 , mushroom  : 0 , berry   : 0 },
            custom : `` },

        clothing : { _isFragile : false ,
            coldProt : 2 , wetProt : 3 , windProt : 3 , storage : 0 , dmgProt : 0 ,
            custom : `` },

        tool : {  _isFragile : false ,
            crafting   : 0 , chopping    : 0 , kindle : 0 , light : 0 ,
            lookout    : 0 , navigation  : 0 ,
            meleeLight : 0 , meleeHeavy  : 0 , ranged : 0 , magic : 0 ,
            custom : `` },

        material : { _isFragile : false ,
            structural : 0 , metallic : 0 , sharp     : 0 , shaft : 0 ,
            cordage    : 0 , cover : 0 , adhesive : 0 , flammable : 0 ,
            custom : `` },

        supply : { _isPerishable : false ,
            exhaustion : 0 , hunger : 0 , hypothermia : 0 , wound    : 0 , 
            herb       : 0 , nut    : 0 , root        : 0 , mushroom : 0 , berry : 0 ,
            custom : `` },
    },
},
/***** 
S H I P
*****/
{   layout: ItemCard , type:Asset.card.item.dinghy , qty: 3 ,
    name:{ de:"Boot", en:"" }, weight: 5 ,
    flavor:{ de:"", en:"" },
    keyword : {
        craft : { _isComplex : true ,
            clothing : {    coldProt   : 0 , wetProt     : 0 , windProt    : 0 , storage   : 0 , dmgProt : 0 },
            tool     : {    crafting   : 0 , chopping    : 0 , kindle      : 0 , light     : 0 ,
                            lookout    : 0 , navigation  : 0 , 
                            meleeLight : 0 , meleeHeavy  : 0 , ranged      : 0 , magic     : 0 },
            material : {    structural : 2 , metallic    : 0 , sharp       : 0 , shaft     : 1 ,
                            cordage    : 1 , cover       : 0 , adhesive    : 0 , flammable : 0 },
            supply   : {    exhaustion : 0 , hunger      : 0 , hypothermia : 0 , wound     : 0 , 
                            herb       : 0 , nut         : 0 , root        : 0 , mushroom  : 0 , berry   : 0 },
            custom : `` },

        clothing : { _isFragile : false ,
            coldProt : 0 , wetProt : 0 , windProt : 0 , storage : 0 , dmgProt : 0 ,
            custom : `` },

        tool : {  _isFragile : false ,
            crafting   : 0 , chopping    : 0 , kindle : 0 , light : 0 ,
            lookout    : 0 , navigation  : 1 ,
            meleeLight : 0 , meleeHeavy  : 0 , ranged : 0 , magic : 0 ,
            custom : `` },

        material : { _isFragile : false ,
            structural : 0 , metallic : 0 , sharp     : 0 , shaft : 0 ,
            cordage    : 0 , cover : 0 , adhesive : 0 , flammable : 0 ,
            custom : `` },

        supply : { _isPerishable : false ,
            exhaustion : 0 , hunger : 0 , hypothermia : 0 , wound    : 0 , 
            herb       : 0 , nut    : 0 , root        : 0 , mushroom : 0 , berry : 0 ,
            custom : `` },
    },
},
{   layout: ItemCard , type:Asset.card.item.boat , qty: 3 ,
    name:{ de:"Schiff", en:"" }, weight: 5 ,
    flavor:{ de:"", en:"" },
    keyword : {
        craft : { _isComplex : true ,
            clothing : {    coldProt   : 0 , wetProt     : 0 , windProt    : 0 , storage   : 0 , dmgProt : 0 },
            tool     : {    crafting   : 0 , chopping    : 0 , kindle      : 0 , light     : 0 ,
                            lookout    : 0 , navigation  : 0 , 
                            meleeLight : 0 , meleeHeavy  : 0 , ranged      : 0 , magic     : 0 },
            material : {    structural : 2 , metallic    : 1 , sharp       : 0 , shaft     : 1 ,
                            cordage    : 1 , cover       : 0 , adhesive    : 1 , flammable : 0 },
            supply   : {    exhaustion : 0 , hunger      : 0 , hypothermia : 0 , wound     : 0 , 
                            herb       : 0 , nut         : 0 , root        : 0 , mushroom  : 0 , berry   : 0 },
            custom : `` },

        clothing : { _isFragile : false ,
            coldProt : 0 , wetProt : 0 , windProt : 0 , storage : 0 , dmgProt : 0 ,
            custom : `` },

        tool : {  _isFragile : false ,
            crafting   : 0 , chopping    : 0 , kindle : 0 , light : 0 ,
            lookout    : 0 , navigation  : 3 ,
            meleeLight : 0 , meleeHeavy  : 0 , ranged : 0 , magic : 0 ,
            custom : `` },

        material : { _isFragile : false ,
            structural : 0 , metallic : 0 , sharp     : 0 , shaft : 0 ,
            cordage    : 0 , cover : 0 , adhesive : 0 , flammable : 0 ,
            custom : `` },

        supply : { _isPerishable : false ,
            exhaustion : 0 , hunger : 0 , hypothermia : 0 , wound    : 0 , 
            herb       : 0 , nut    : 0 , root        : 0 , mushroom : 0 , berry : 0 ,
            custom : `` },
    },
},
]





const CharacterCards = [ 
/***** 
C H A R A C T E R
Kolonist
*****/
    {   layout: CharacterCard, type:Asset.card.character.colonist, qty:4,
        name:{de:Asset.spacer},
        ability: [  ``,
                    ``,
                    ``,
                    ``,
                    ``,
                    ``,
                    `` ],
        crafting: [ `` ],
        passion: [ 0 , 0 , 0 ],
    },
    {   layout: CharacterCard, type:Asset.card.character.colonist, qty:1,
        name:{de:"Landarbeiter"}, // Era-appropriate for a general gatherer
        ability: [  `+ ${Asset.tile.action.gathering.icon}`,
                    ``,
                    ``,
                    ``,
                    ``,
                    ``,
                    `` ],
        crafting: [ `Messer` ],
        passion: [ 1 , 0 , 0 ], // STR 
    },
    {   layout: CharacterCard, type:Asset.card.character.colonist, qty:1,
        name:{de:"Wildhüter"}, // Gamekeeper fits the hunting/trapping theme perfectly
        ability: [  `+ ${Asset.tile.action.hunting.icon}`,
                    ``,
                    ``,
                    ``,
                    ``,
                    ``,
                    `` ],
        crafting: [ `Falle` ],
        passion: [ 0 , 1 , 0 ], // Shifted to DEX: Trapping is finesse and patience
    },
    {   layout: CharacterCard, type:Asset.card.character.colonist, qty:1,
        name:{de:"Holzfäller"},
        ability: [  `+ ${Asset.tile.action.chopping.icon}`,
                    ``,
                    ``,
                    ``,
                    ``,
                    ``,
                    `` ],
        crafting: [ `Axt` ],
        passion: [ 1 , 0 , 0 ], // STR
    },
    {   layout: CharacterCard, type:Asset.card.character.colonist, qty:1,
        name:{de:"Botaniker"},
        ability: [  `Einmal pro Runde:`,
                    `Wenn vorhanden: `,
                    `sieh einen`,
                    `${Asset.keyword.supply.herb.icon}${Asset.keyword.supply.nut.icon}${Asset.keyword.supply.root.icon}${Asset.keyword.supply.mushroom.icon}${Asset.keyword.supply.berry.icon} Effekt`,
                    ``,
                    ``,
                    ``, ],
        crafting: [ `Pflanzenextrakt` ],
        passion: [ 0 , 0 , 1 ], // WIS
    },
    {   layout: CharacterCard, type:Asset.card.character.colonist, qty:1,
        name:{de:"Zimmermann"}, // Carpenter
        ability: [  `Unterschlupf`,
                    `verbessern:`,
                    `- ${Asset.keyword.material.structural.icon}`,
                    ``,
                    ``,
                    ``,
                    ``, ],
        crafting: [ `Struktur` ],
        passion: [ 1 , 0 , 0 ], // STR 
    },
    {   layout: CharacterCard, type:Asset.card.character.colonist, qty:1,
        name:{de:"Schneider"}, // Tailor
        ability: [  ``,
                    ``,
                    ``,
                    ``,
                    ``,
                    ``,
                    `` ],
        crafting: [ `Kleidung` ],
        passion: [ 0 , 1 , 0 ], // Shifted to DEX: Sewing/weaving requires dexterity
    },
    {   layout: CharacterCard, type:Asset.card.character.colonist, qty:1,
        name:{de:"Gerber"}, // Tanner/Leatherworker
        ability: [  ``,
                    ``,
                    ``,
                    ``,
                    ``,
                    ``,
                    `` ],
        crafting: [ `Beutel` ],
        passion: [ 0 , 1 , 0 ], // DEX
    },
    {   layout: CharacterCard, type:Asset.card.character.colonist, qty:1,
        name:{de:"Seiler"}, // Ropemaker
        ability: [  ``,
                    ``,
                    ``,
                    ``,
                    ``,
                    ``,
                    `` ], // Rewards gathering raw materials for threads
        crafting: [ `Naturfaden` ],
        passion: [ 0 , 1 , 0 ], // DEX
    },
    {   layout: CharacterCard, type:Asset.card.character.colonist, qty:1,
        name:{de:"Feldscher"}, // 18th-century field surgeon/medic
        ability: [  `Einmal pro Runde:`,
                    `Nutze ${Asset.keyword.material.sharp.icon} und`,
                    `verbrauche ${Asset.keyword.material.cordage.icon}/${Asset.keyword.material.cover.icon}:`,
                    `jemand ${Asset.keyword.supply.wound.icon}`,
                    ``,
                    ``,
                    ``  ], // Changed "erhält" (receives wound) to "erholt" (heals wound) assuming a typo
        crafting: [ `Bandage` ],
        passion: [ 0 , 1 , 0 ], // Shifted to DEX: Surgery is a steady hand, not just book smarts
    },
    {   layout: CharacterCard, type:Asset.card.character.colonist, qty:1,
        name:{de:"Pfarrer"}, // Priest/Pastor
        ability: [  `Einmal pro Runde:`,
                    `Selber ${Asset.condition.exhaustion.icon}${Asset.condition.exhaustion.icon}`,
                    `Alle anderen ${Asset.keyword.supply.exhaustion.icon}`,
                    `` ], // Added "entfernen" for clarity
        crafting: [ ``,
                    ``,
                    ``,
                    `` ],
        passion: [ 0 , 0 , 1 ], // WIS
    },
    {   layout: CharacterCard, type:Asset.card.character.colonist, qty:1,
        name:{de:"Wirt"}, // Innkeeper/Tavernkeep for the colonist cook
        ability: [  `Für das erste ${Asset.keyword.supply.hunger.icon}`,
                    `pro Runde, ein`,
                    `weiteres ${Asset.keyword.supply.hunger.icon} für jemanden`,
                    ``,
                    ``,
                    ``, ],
        crafting: [ `` ],
        passion: [ 0 , 0 , 1 ], // WIS
    },
/***** 
C H A R A C T E R
Seefahrer
*****/
    {   layout: CharacterCard, type:Asset.card.character.seaman, qty:4,
        name:{de:Asset.spacer},
        ability: [  ``,
                    ``,
                    ``,
                    ``,
                    ``,
                    ``,
                    `` ],
        crafting: [ `` ],
        passion: [ 0 , 0 , 0 ],
    },
    {   layout: CharacterCard, type:Asset.card.character.seaman, qty:1,
        name:{de:"Kapitän"},
        ability: [  `Nach Abstimmung:`,
                    `${Asset.card.character.seaman.icon} stimmen wie du,`,
                    `alle Umgestimmten`,
                    `und du: ${Asset.condition.exhaustion.icon}`,
                    ``,
                    ``,
                    ``, ],
        crafting: [ `` ],
        passion: [ 0 , 0 , 1 ], // WIS
    },
    {   layout: CharacterCard, type:Asset.card.character.seaman, qty:1,
        name:{de:"Erster Offizier"},
        ability: [  `Einmal pro Runde:`,
                    `Ein ${Asset.card.character.seaman.icon} tut`,
                    `was du willst`,
                    `Beide ${Asset.condition.exhaustion.icon}`,
                    ``,
                    ``,
                    ``  ],
        crafting: [ `` ],
        passion: [ 1 , 0 , 0 ], // STR: Enforcing physical order
    },
    {   layout: CharacterCard, type:Asset.card.character.seaman, qty:1,
        name:{de:"Navigator"},
        ability: [  `Flucht mit`,
                    `dem Schiff:`,
                    `${Asset.keyword.tool.navigation.icon} ${Asset.keyword.tool.navigation.icon}`,
                    ``,
                    ``,
                    ``,
                    `` ],
        crafting: [ `` ],
        passion: [ 0 , 0 , 1 ], // WIS
    },
    {   layout: CharacterCard, type:Asset.card.character.seaman, qty:1,
        name:{de:"Matrose"}, // Standard Sailor
        ability: [  `Das erste ${Asset.keyword.weight.icon}`,
                    `zählt nicht`,
                    ``,
                    ``,
                    ``,
                    ``,
                    `` ],
        crafting: [ `` ],
        passion: [ 1 , 0 , 0 ], // STR
    },
    {   layout: CharacterCard, type:Asset.card.character.seaman, qty:1,
        name:{de:"Schiffszimmermann"}, // Ship's Carpenter
        ability: [  `Schiff`,
                    `verbessern:`,
                    `- ${Asset.keyword.material.structural.icon}`,
                    ``,
                    ``,
                    ``,
                    `` ],
        crafting: [ `Struktur` ],
        passion: [ 1 , 0 , 0 ], // STR
    },
    {   layout: CharacterCard, type:Asset.card.character.seaman, qty:1,
        name:{de:"Smutje"}, // Authentic 18th-century German naval slang for Cook
        ability: [  `Für das erste ${Asset.keyword.supply.hunger.icon}`,
                    `pro Runde, ein`,
                    `weiteres ${Asset.keyword.supply.hunger.icon} für jemanden`,
                    ``,
                    ``,
                    `` ],
        crafting: [ `` ],
        passion: [ 0 , 0 , 1 ], // WIS
    },
]





const ModifierCards = [ 
/***** 
A T T R I B U T E
*****/
    //{ layout:AttributeCard, qty : 1 , attribute : [1,1,1] },
        
    //{ layout:AttributeCard, qty : 1 , attribute : [2,1,1] },
    //{ layout:AttributeCard, qty : 1 , attribute : [1,2,1] },
    //{ layout:AttributeCard, qty : 1 , attribute : [1,1,2] },

    { layout:AttributeCard, qty : 2 , attribute : [2,2,1] },
    { layout:AttributeCard, qty : 2 , attribute : [2,1,2] },
    { layout:AttributeCard, qty : 2 , attribute : [1,2,2] },
        { layout:AttributeCard, qty : 1 , attribute : [3,1,1] },
        { layout:AttributeCard, qty : 1 , attribute : [1,3,1] },
        { layout:AttributeCard, qty : 1 , attribute : [1,1,3] },

    { layout:AttributeCard, qty : 3 , attribute : [2,2,2] },
        { layout:AttributeCard, qty : 2 , attribute : [1,2,3] },
        { layout:AttributeCard, qty : 2 , attribute : [2,1,3] },
        { layout:AttributeCard, qty : 2 , attribute : [1,3,2] },
        { layout:AttributeCard, qty : 2 , attribute : [2,3,1] },
        { layout:AttributeCard, qty : 2 , attribute : [3,1,2] },
        { layout:AttributeCard, qty : 2 , attribute : [3,2,1] },

    { layout:AttributeCard, qty : 2 , attribute : [3,2,2] },
    { layout:AttributeCard, qty : 2 , attribute : [2,3,2] },
    { layout:AttributeCard, qty : 2 , attribute : [2,2,3] },
        { layout:AttributeCard, qty : 1 , attribute : [1,3,3] },
        { layout:AttributeCard, qty : 1 , attribute : [3,1,3] },
        { layout:AttributeCard, qty : 1 , attribute : [3,3,1] },

    //{ layout:AttributeCard, qty : 1 , attribute : [2,3,3] },
    //{ layout:AttributeCard, qty : 1 , attribute : [3,2,3] },
    //{ layout:AttributeCard, qty : 1 , attribute : [3,3,2] },

    //{ layout:AttributeCard, qty : 1 , attribute : [3,3,3] },
/***** 
M O D I F I E R
*****/
    { layout:TraitCard,type:Asset.card.modifier.trait.pos, qty : 1 , trait : ["1","1","1"] },

    //{ layout:TraitCard,type:Asset.card.modifier.trait.neg, qty : 1 , trait : ["1","1","1"] },

    //{ layout:TraitCard,type:Asset.card.modifier.trait.neu, qty : 1 , trait : ["1","1","1"] },
]

